// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: events/req_get_event.proto

/* eslint-disable */

export const protobufPackage = "types_events";

/** GET: /ontology/v1/events/:event_id */
export interface RequestGetEvent {
  event_id: string;
}
