// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: events/req_create_event.proto

/* eslint-disable */

export const protobufPackage = "types_events";

/** POST: /ontology/v1/events/create */
export interface RequestCreateEvent {
  general_data: GeneralData | undefined;
  transaction_data?: TransactionData | undefined;
  action_data?: ActionData | undefined;
  digital_data?: DigitalData | undefined;
  device_data?: DeviceData | undefined;
  location_data?: LocationData | undefined;
  custom_data: { [key: string]: string };
  options?: Options | undefined;
}

export interface RequestCreateEvent_CustomDataEntry {
  key: string;
  value: string;
}

export interface GeneralData {
  event_id: string;
  event_type: string;
  event_time: string;
  event_subtype?: string | undefined;
  status?: string | undefined;
  tags: string[];
}

export interface TransactionData {
  amount: number;
  sent_amount?: number | undefined;
  sent_currency?: string | undefined;
  sender_entity_id?: string | undefined;
  sender_entity_type?: string | undefined;
  sender_instrument_id?: string | undefined;
  received_amount?: number | undefined;
  received_currency?: string | undefined;
  receiver_entity_id?: string | undefined;
  receiver_entity_type?: string | undefined;
  receiver_instrument_id?: string | undefined;
  exchange_rate?: number | undefined;
  transaction_hash?: string | undefined;
  usd_conversion_notes?: string | undefined;
  internal_fee?: number | undefined;
  external_fee?: number | undefined;
}

export interface ActionData {
  action_type: string;
  action_details?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  instrument_id?: string | undefined;
}

export interface DigitalData {
  ip_address?: string | undefined;
  client_fingerprint?: string | undefined;
}

export interface DeviceData {
  request_id?: string | undefined;
  encrypted_device_payload?: string | undefined;
  associated_entity_ids: string[];
}

export interface LocationData {
  type?: string | undefined;
  building_number?: string | undefined;
  unit_number?: string | undefined;
  street_name?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postal_code?: string | undefined;
  country?: string | undefined;
  id?: string | undefined;
}

export interface Options {
  monitor?: boolean | undefined;
  resolve_geoip?: boolean | undefined;
  link_digital_data_to_entity?: boolean | undefined;
  linked_entity?: string | undefined;
  merge_custom_data?: boolean | undefined;
  upsert_on_conflict?: boolean | undefined;
}
