// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: events/res_create_event.proto

/* eslint-disable */

export const protobufPackage = "types_events";

/** Response for POST: /ontology/v1/events/create */
export interface ResponseCreateEvent {
  code: string;
  message: string;
  data?: EventData | undefined;
}

export interface EventData {
  event_id: string;
  event_type: string;
  event_time: string;
  status: string;
  created_at: string;
  updated_at: string;
}
