// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: events/res_get_event.proto

/* eslint-disable */
import type {
  GeneralData,
  LocationData,
  TransactionData,
} from "./req_create_event";

export const protobufPackage = "types_events";

/** Response for GET: /ontology/v1/events/:event_id */
export interface ResponseGetEvent {
  code: string;
  message: string;
  data: ResponseGetEvent_EventData | undefined;
}

export interface ResponseGetEvent_EventData {
  general_data: GeneralData | undefined;
  is_cold_store: boolean;
  custom_data: { [key: string]: string };
  digital_data?: ResponseGetEvent_DigitalData | undefined;
  location_data: LocationData[];
  transaction_data?: TransactionData | undefined;
}

export interface ResponseGetEvent_EventData_CustomDataEntry {
  key: string;
  value: string;
}

export interface ResponseGetEvent_DigitalData {
  ip_addresses: string[];
  client_fingerprints: string[];
}
