// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: operators/res_list_operators.proto

/* eslint-disable */

export const protobufPackage = "types_operators";

/** Response for GET: /ontology/v1/operators/list */
export interface ResponseListOperators {
  code: string;
  message: string;
  results: OperatorItem[];
}

export interface OperatorItem {
  name: string;
  type: string;
  value: string;
  symbol: string;
}
