// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/req_update_feature.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUpdateFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description"`
	IsActive      *bool                  `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdateFeature) Reset() {
	*x = RequestUpdateFeature{}
	mi := &file_ontology_req_update_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdateFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateFeature) ProtoMessage() {}

func (x *RequestUpdateFeature) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_req_update_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateFeature.ProtoReflect.Descriptor instead.
func (*RequestUpdateFeature) Descriptor() ([]byte, []int) {
	return file_ontology_req_update_feature_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUpdateFeature) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RequestUpdateFeature) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RequestUpdateFeature) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

var File_ontology_req_update_feature_proto protoreflect.FileDescriptor

const file_ontology_req_update_feature_proto_rawDesc = "" +
	"\n" +
	"!ontology/req_update_feature.proto\x12\x0etypes_ontology\"\x9f\x01\n" +
	"\x14RequestUpdateFeature\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x03 \x01(\bH\x02R\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_is_activeB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_req_update_feature_proto_rawDescOnce sync.Once
	file_ontology_req_update_feature_proto_rawDescData []byte
)

func file_ontology_req_update_feature_proto_rawDescGZIP() []byte {
	file_ontology_req_update_feature_proto_rawDescOnce.Do(func() {
		file_ontology_req_update_feature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_req_update_feature_proto_rawDesc), len(file_ontology_req_update_feature_proto_rawDesc)))
	})
	return file_ontology_req_update_feature_proto_rawDescData
}

var file_ontology_req_update_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ontology_req_update_feature_proto_goTypes = []any{
	(*RequestUpdateFeature)(nil), // 0: types_ontology.RequestUpdateFeature
}
var file_ontology_req_update_feature_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ontology_req_update_feature_proto_init() }
func file_ontology_req_update_feature_proto_init() {
	if File_ontology_req_update_feature_proto != nil {
		return
	}
	file_ontology_req_update_feature_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_req_update_feature_proto_rawDesc), len(file_ontology_req_update_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_req_update_feature_proto_goTypes,
		DependencyIndexes: file_ontology_req_update_feature_proto_depIdxs,
		MessageInfos:      file_ontology_req_update_feature_proto_msgTypes,
	}.Build()
	File_ontology_req_update_feature_proto = out.File
	file_ontology_req_update_feature_proto_goTypes = nil
	file_ontology_req_update_feature_proto_depIdxs = nil
}
