// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/req_update_entity.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUpdateEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description"`
	Code          *string                `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code"` // Not for FE to edit
	DisplayOrder  *int32                 `protobuf:"varint,4,opt,name=display_order,json=displayOrder,proto3,oneof" json:"display_order"`
	IsStart       *bool                  `protobuf:"varint,5,opt,name=is_start,json=isStart,proto3,oneof" json:"is_start"`
	IsTerminal    *bool                  `protobuf:"varint,6,opt,name=is_terminal,json=isTerminal,proto3,oneof" json:"is_terminal"`
	FeatureId     *int64                 `protobuf:"varint,7,opt,name=feature_id,json=featureId,proto3,oneof" json:"feature_id"`
	ApiIds        []int64                `protobuf:"varint,8,rep,packed,name=api_ids,json=apiIds,proto3" json:"api_ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdateEntity) Reset() {
	*x = RequestUpdateEntity{}
	mi := &file_ontology_req_update_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateEntity) ProtoMessage() {}

func (x *RequestUpdateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_req_update_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateEntity.ProtoReflect.Descriptor instead.
func (*RequestUpdateEntity) Descriptor() ([]byte, []int) {
	return file_ontology_req_update_entity_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUpdateEntity) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RequestUpdateEntity) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RequestUpdateEntity) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *RequestUpdateEntity) GetDisplayOrder() int32 {
	if x != nil && x.DisplayOrder != nil {
		return *x.DisplayOrder
	}
	return 0
}

func (x *RequestUpdateEntity) GetIsStart() bool {
	if x != nil && x.IsStart != nil {
		return *x.IsStart
	}
	return false
}

func (x *RequestUpdateEntity) GetIsTerminal() bool {
	if x != nil && x.IsTerminal != nil {
		return *x.IsTerminal
	}
	return false
}

func (x *RequestUpdateEntity) GetFeatureId() int64 {
	if x != nil && x.FeatureId != nil {
		return *x.FeatureId
	}
	return 0
}

func (x *RequestUpdateEntity) GetApiIds() []int64 {
	if x != nil {
		return x.ApiIds
	}
	return nil
}

var File_ontology_req_update_entity_proto protoreflect.FileDescriptor

const file_ontology_req_update_entity_proto_rawDesc = "" +
	"\n" +
	" ontology/req_update_entity.proto\x12\x0etypes_ontology\"\xfb\x02\n" +
	"\x13RequestUpdateEntity\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x03 \x01(\tH\x02R\x04code\x88\x01\x01\x12(\n" +
	"\rdisplay_order\x18\x04 \x01(\x05H\x03R\fdisplayOrder\x88\x01\x01\x12\x1e\n" +
	"\bis_start\x18\x05 \x01(\bH\x04R\aisStart\x88\x01\x01\x12$\n" +
	"\vis_terminal\x18\x06 \x01(\bH\x05R\n" +
	"isTerminal\x88\x01\x01\x12\"\n" +
	"\n" +
	"feature_id\x18\a \x01(\x03H\x06R\tfeatureId\x88\x01\x01\x12\x17\n" +
	"\aapi_ids\x18\b \x03(\x03R\x06apiIdsB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_codeB\x10\n" +
	"\x0e_display_orderB\v\n" +
	"\t_is_startB\x0e\n" +
	"\f_is_terminalB\r\n" +
	"\v_feature_idB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_req_update_entity_proto_rawDescOnce sync.Once
	file_ontology_req_update_entity_proto_rawDescData []byte
)

func file_ontology_req_update_entity_proto_rawDescGZIP() []byte {
	file_ontology_req_update_entity_proto_rawDescOnce.Do(func() {
		file_ontology_req_update_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_req_update_entity_proto_rawDesc), len(file_ontology_req_update_entity_proto_rawDesc)))
	})
	return file_ontology_req_update_entity_proto_rawDescData
}

var file_ontology_req_update_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ontology_req_update_entity_proto_goTypes = []any{
	(*RequestUpdateEntity)(nil), // 0: types_ontology.RequestUpdateEntity
}
var file_ontology_req_update_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ontology_req_update_entity_proto_init() }
func file_ontology_req_update_entity_proto_init() {
	if File_ontology_req_update_entity_proto != nil {
		return
	}
	file_ontology_req_update_entity_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_req_update_entity_proto_rawDesc), len(file_ontology_req_update_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_req_update_entity_proto_goTypes,
		DependencyIndexes: file_ontology_req_update_entity_proto_depIdxs,
		MessageInfos:      file_ontology_req_update_entity_proto_msgTypes,
	}.Build()
	File_ontology_req_update_entity_proto = out.File
	file_ontology_req_update_entity_proto_goTypes = nil
	file_ontology_req_update_entity_proto_depIdxs = nil
}
