// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ontology/req_create_feature.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreateFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreateFeature) Reset() {
	*x = RequestCreateFeature{}
	mi := &file_ontology_req_create_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreateFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateFeature) ProtoMessage() {}

func (x *RequestCreateFeature) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_req_create_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateFeature.ProtoReflect.Descriptor instead.
func (*RequestCreateFeature) Descriptor() ([]byte, []int) {
	return file_ontology_req_create_feature_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateFeature) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RequestCreateFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestCreateFeature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestCreateFeature) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_ontology_req_create_feature_proto protoreflect.FileDescriptor

const file_ontology_req_create_feature_proto_rawDesc = "" +
	"\n" +
	"!ontology/req_create_feature.proto\x12\x0etypes_ontology\"}\n" +
	"\x14RequestCreateFeature\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActiveB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_req_create_feature_proto_rawDescOnce sync.Once
	file_ontology_req_create_feature_proto_rawDescData []byte
)

func file_ontology_req_create_feature_proto_rawDescGZIP() []byte {
	file_ontology_req_create_feature_proto_rawDescOnce.Do(func() {
		file_ontology_req_create_feature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_req_create_feature_proto_rawDesc), len(file_ontology_req_create_feature_proto_rawDesc)))
	})
	return file_ontology_req_create_feature_proto_rawDescData
}

var file_ontology_req_create_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ontology_req_create_feature_proto_goTypes = []any{
	(*RequestCreateFeature)(nil), // 0: types_ontology.RequestCreateFeature
}
var file_ontology_req_create_feature_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ontology_req_create_feature_proto_init() }
func file_ontology_req_create_feature_proto_init() {
	if File_ontology_req_create_feature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_req_create_feature_proto_rawDesc), len(file_ontology_req_create_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_req_create_feature_proto_goTypes,
		DependencyIndexes: file_ontology_req_create_feature_proto_depIdxs,
		MessageInfos:      file_ontology_req_create_feature_proto_msgTypes,
	}.Build()
	File_ontology_req_create_feature_proto = out.File
	file_ontology_req_create_feature_proto_goTypes = nil
	file_ontology_req_create_feature_proto_depIdxs = nil
}
