// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/req_create_entity.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreateEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureId     int64                  `protobuf:"varint,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	DisplayOrder  int32                  `protobuf:"varint,5,opt,name=display_order,json=displayOrder,proto3" json:"display_order"`
	IsStart       bool                   `protobuf:"varint,6,opt,name=is_start,json=isStart,proto3" json:"is_start"`
	IsTerminal    bool                   `protobuf:"varint,7,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal"`
	ApiIds        []int64                `protobuf:"varint,8,rep,packed,name=api_ids,json=apiIds,proto3" json:"api_ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreateEntity) Reset() {
	*x = RequestCreateEntity{}
	mi := &file_ontology_req_create_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateEntity) ProtoMessage() {}

func (x *RequestCreateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_req_create_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateEntity.ProtoReflect.Descriptor instead.
func (*RequestCreateEntity) Descriptor() ([]byte, []int) {
	return file_ontology_req_create_entity_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateEntity) GetFeatureId() int64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

func (x *RequestCreateEntity) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RequestCreateEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestCreateEntity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestCreateEntity) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *RequestCreateEntity) GetIsStart() bool {
	if x != nil {
		return x.IsStart
	}
	return false
}

func (x *RequestCreateEntity) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *RequestCreateEntity) GetApiIds() []int64 {
	if x != nil {
		return x.ApiIds
	}
	return nil
}

var File_ontology_req_create_entity_proto protoreflect.FileDescriptor

const file_ontology_req_create_entity_proto_rawDesc = "" +
	"\n" +
	" ontology/req_create_entity.proto\x12\x0etypes_ontology\"\xf8\x01\n" +
	"\x13RequestCreateEntity\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x01 \x01(\x03R\tfeatureId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rdisplay_order\x18\x05 \x01(\x05R\fdisplayOrder\x12\x19\n" +
	"\bis_start\x18\x06 \x01(\bR\aisStart\x12\x1f\n" +
	"\vis_terminal\x18\a \x01(\bR\n" +
	"isTerminal\x12\x17\n" +
	"\aapi_ids\x18\b \x03(\x03R\x06apiIdsB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_req_create_entity_proto_rawDescOnce sync.Once
	file_ontology_req_create_entity_proto_rawDescData []byte
)

func file_ontology_req_create_entity_proto_rawDescGZIP() []byte {
	file_ontology_req_create_entity_proto_rawDescOnce.Do(func() {
		file_ontology_req_create_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_req_create_entity_proto_rawDesc), len(file_ontology_req_create_entity_proto_rawDesc)))
	})
	return file_ontology_req_create_entity_proto_rawDescData
}

var file_ontology_req_create_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ontology_req_create_entity_proto_goTypes = []any{
	(*RequestCreateEntity)(nil), // 0: types_ontology.RequestCreateEntity
}
var file_ontology_req_create_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ontology_req_create_entity_proto_init() }
func file_ontology_req_create_entity_proto_init() {
	if File_ontology_req_create_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_req_create_entity_proto_rawDesc), len(file_ontology_req_create_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_req_create_entity_proto_goTypes,
		DependencyIndexes: file_ontology_req_create_entity_proto_depIdxs,
		MessageInfos:      file_ontology_req_create_entity_proto_msgTypes,
	}.Build()
	File_ontology_req_create_entity_proto = out.File
	file_ontology_req_create_entity_proto_goTypes = nil
	file_ontology_req_create_entity_proto_depIdxs = nil
}
