// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ontology/req_create_team.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreateTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	SlackChannel  string                 `protobuf:"bytes,2,opt,name=slack_channel,json=slackChannel,proto3" json:"slack_channel"`
	OncallEmail   string                 `protobuf:"bytes,3,opt,name=oncall_email,json=oncallEmail,proto3" json:"oncall_email"` //Comma separated emails
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreateTeam) Reset() {
	*x = RequestCreateTeam{}
	mi := &file_ontology_req_create_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreateTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateTeam) ProtoMessage() {}

func (x *RequestCreateTeam) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_req_create_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateTeam.ProtoReflect.Descriptor instead.
func (*RequestCreateTeam) Descriptor() ([]byte, []int) {
	return file_ontology_req_create_team_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateTeam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestCreateTeam) GetSlackChannel() string {
	if x != nil {
		return x.SlackChannel
	}
	return ""
}

func (x *RequestCreateTeam) GetOncallEmail() string {
	if x != nil {
		return x.OncallEmail
	}
	return ""
}

var File_ontology_req_create_team_proto protoreflect.FileDescriptor

const file_ontology_req_create_team_proto_rawDesc = "" +
	"\n" +
	"\x1eontology/req_create_team.proto\x12\x0etypes_ontology\"o\n" +
	"\x11RequestCreateTeam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rslack_channel\x18\x02 \x01(\tR\fslackChannel\x12!\n" +
	"\foncall_email\x18\x03 \x01(\tR\voncallEmailB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_req_create_team_proto_rawDescOnce sync.Once
	file_ontology_req_create_team_proto_rawDescData []byte
)

func file_ontology_req_create_team_proto_rawDescGZIP() []byte {
	file_ontology_req_create_team_proto_rawDescOnce.Do(func() {
		file_ontology_req_create_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_req_create_team_proto_rawDesc), len(file_ontology_req_create_team_proto_rawDesc)))
	})
	return file_ontology_req_create_team_proto_rawDescData
}

var file_ontology_req_create_team_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ontology_req_create_team_proto_goTypes = []any{
	(*RequestCreateTeam)(nil), // 0: types_ontology.RequestCreateTeam
}
var file_ontology_req_create_team_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ontology_req_create_team_proto_init() }
func file_ontology_req_create_team_proto_init() {
	if File_ontology_req_create_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_req_create_team_proto_rawDesc), len(file_ontology_req_create_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_req_create_team_proto_goTypes,
		DependencyIndexes: file_ontology_req_create_team_proto_depIdxs,
		MessageInfos:      file_ontology_req_create_team_proto_msgTypes,
	}.Build()
	File_ontology_req_create_team_proto = out.File
	file_ontology_req_create_team_proto_goTypes = nil
	file_ontology_req_create_team_proto_depIdxs = nil
}
