// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_update_feature.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseUpdateFeature struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          string                        `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        *ResponseUpdateFeature_Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUpdateFeature) Reset() {
	*x = ResponseUpdateFeature{}
	mi := &file_ontology_res_update_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpdateFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdateFeature) ProtoMessage() {}

func (x *ResponseUpdateFeature) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_update_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdateFeature.ProtoReflect.Descriptor instead.
func (*ResponseUpdateFeature) Descriptor() ([]byte, []int) {
	return file_ontology_res_update_feature_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseUpdateFeature) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseUpdateFeature) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseUpdateFeature) GetResult() *ResponseUpdateFeature_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseUpdateFeature_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUpdateFeature_Result) Reset() {
	*x = ResponseUpdateFeature_Result{}
	mi := &file_ontology_res_update_feature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpdateFeature_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdateFeature_Result) ProtoMessage() {}

func (x *ResponseUpdateFeature_Result) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_update_feature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdateFeature_Result.ProtoReflect.Descriptor instead.
func (*ResponseUpdateFeature_Result) Descriptor() ([]byte, []int) {
	return file_ontology_res_update_feature_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseUpdateFeature_Result) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseUpdateFeature_Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseUpdateFeature_Result) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseUpdateFeature_Result) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseUpdateFeature_Result) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ResponseUpdateFeature_Result) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseUpdateFeature_Result) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_ontology_res_update_feature_proto protoreflect.FileDescriptor

const file_ontology_res_update_feature_proto_rawDesc = "" +
	"\n" +
	"!ontology/res_update_feature.proto\x12\x0etypes_ontology\"\xcb\x02\n" +
	"\x15ResponseUpdateFeature\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x06result\x18\x03 \x01(\v2,.types_ontology.ResponseUpdateFeature.ResultR\x06result\x1a\xbd\x01\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAtB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_update_feature_proto_rawDescOnce sync.Once
	file_ontology_res_update_feature_proto_rawDescData []byte
)

func file_ontology_res_update_feature_proto_rawDescGZIP() []byte {
	file_ontology_res_update_feature_proto_rawDescOnce.Do(func() {
		file_ontology_res_update_feature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_update_feature_proto_rawDesc), len(file_ontology_res_update_feature_proto_rawDesc)))
	})
	return file_ontology_res_update_feature_proto_rawDescData
}

var file_ontology_res_update_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ontology_res_update_feature_proto_goTypes = []any{
	(*ResponseUpdateFeature)(nil),        // 0: types_ontology.ResponseUpdateFeature
	(*ResponseUpdateFeature_Result)(nil), // 1: types_ontology.ResponseUpdateFeature.Result
}
var file_ontology_res_update_feature_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseUpdateFeature.result:type_name -> types_ontology.ResponseUpdateFeature.Result
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ontology_res_update_feature_proto_init() }
func file_ontology_res_update_feature_proto_init() {
	if File_ontology_res_update_feature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_update_feature_proto_rawDesc), len(file_ontology_res_update_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_update_feature_proto_goTypes,
		DependencyIndexes: file_ontology_res_update_feature_proto_depIdxs,
		MessageInfos:      file_ontology_res_update_feature_proto_msgTypes,
	}.Build()
	File_ontology_res_update_feature_proto = out.File
	file_ontology_res_update_feature_proto_goTypes = nil
	file_ontology_res_update_feature_proto_depIdxs = nil
}
