// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_apis.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetApis struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          string                      `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetApis_Api      `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetApis_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetApis) Reset() {
	*x = ResponseGetApis{}
	mi := &file_ontology_res_get_apis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetApis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetApis) ProtoMessage() {}

func (x *ResponseGetApis) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_apis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetApis.ProtoReflect.Descriptor instead.
func (*ResponseGetApis) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_apis_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetApis) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetApis) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetApis) GetResult() []*ResponseGetApis_Api {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetApis) GetPagination() *ResponseGetApis_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetApis_Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol"`
	IsInternal    bool                   `protobuf:"varint,5,opt,name=is_internal,json=isInternal,proto3" json:"is_internal"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetApis_Api) Reset() {
	*x = ResponseGetApis_Api{}
	mi := &file_ontology_res_get_apis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetApis_Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetApis_Api) ProtoMessage() {}

func (x *ResponseGetApis_Api) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_apis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetApis_Api.ProtoReflect.Descriptor instead.
func (*ResponseGetApis_Api) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_apis_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetApis_Api) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetApis_Api) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ResponseGetApis_Api) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ResponseGetApis_Api) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ResponseGetApis_Api) GetIsInternal() bool {
	if x != nil {
		return x.IsInternal
	}
	return false
}

func (x *ResponseGetApis_Api) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ResponseGetApis_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetApis_Pagination) Reset() {
	*x = ResponseGetApis_Pagination{}
	mi := &file_ontology_res_get_apis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetApis_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetApis_Pagination) ProtoMessage() {}

func (x *ResponseGetApis_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_apis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetApis_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetApis_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_apis_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetApis_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetApis_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetApis_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetApis_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_apis_proto protoreflect.FileDescriptor

const file_ontology_res_get_apis_proto_rawDesc = "" +
	"\n" +
	"\x1bontology/res_get_apis.proto\x12\x0etypes_ontology\"\x81\x04\n" +
	"\x0fResponseGetApis\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x06result\x18\x03 \x03(\v2#.types_ontology.ResponseGetApis.ApiR\x06result\x12J\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2*.types_ontology.ResponseGetApis.PaginationR\n" +
	"pagination\x1a\xa5\x01\n" +
	"\x03Api\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vis_internal\x18\x05 \x01(\bR\n" +
	"isInternal\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_apis_proto_rawDescOnce sync.Once
	file_ontology_res_get_apis_proto_rawDescData []byte
)

func file_ontology_res_get_apis_proto_rawDescGZIP() []byte {
	file_ontology_res_get_apis_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_apis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_apis_proto_rawDesc), len(file_ontology_res_get_apis_proto_rawDesc)))
	})
	return file_ontology_res_get_apis_proto_rawDescData
}

var file_ontology_res_get_apis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_apis_proto_goTypes = []any{
	(*ResponseGetApis)(nil),            // 0: types_ontology.ResponseGetApis
	(*ResponseGetApis_Api)(nil),        // 1: types_ontology.ResponseGetApis.Api
	(*ResponseGetApis_Pagination)(nil), // 2: types_ontology.ResponseGetApis.Pagination
}
var file_ontology_res_get_apis_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetApis.result:type_name -> types_ontology.ResponseGetApis.Api
	2, // 1: types_ontology.ResponseGetApis.pagination:type_name -> types_ontology.ResponseGetApis.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_apis_proto_init() }
func file_ontology_res_get_apis_proto_init() {
	if File_ontology_res_get_apis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_apis_proto_rawDesc), len(file_ontology_res_get_apis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_apis_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_apis_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_apis_proto_msgTypes,
	}.Build()
	File_ontology_res_get_apis_proto = out.File
	file_ontology_res_get_apis_proto_goTypes = nil
	file_ontology_res_get_apis_proto_depIdxs = nil
}
