// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_feature_metrics.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetFeatureMetrics struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Code          string                                   `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        *ResponseGetFeatureMetrics_FeatureMetric `protobuf:"bytes,3,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatureMetrics) Reset() {
	*x = ResponseGetFeatureMetrics{}
	mi := &file_ontology_res_get_feature_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureMetrics) ProtoMessage() {}

func (x *ResponseGetFeatureMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureMetrics.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureMetrics) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetFeatureMetrics) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetFeatureMetrics) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetFeatureMetrics) GetResult() *ResponseGetFeatureMetrics_FeatureMetric {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseGetFeatureMetrics_FeatureMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowStart   string                 `protobuf:"bytes,1,opt,name=window_start,json=windowStart,proto3" json:"window_start"`
	WindowMinutes int32                  `protobuf:"varint,2,opt,name=window_minutes,json=windowMinutes,proto3" json:"window_minutes"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate"`
	FailureRate   float64                `protobuf:"fixed64,5,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate"`
	P50DurationMs float64                `protobuf:"fixed64,6,opt,name=p50_duration_ms,json=p50DurationMs,proto3" json:"p50_duration_ms"`
	P95DurationMs float64                `protobuf:"fixed64,7,opt,name=p95_duration_ms,json=p95DurationMs,proto3" json:"p95_duration_ms"`
	P99DurationMs float64                `protobuf:"fixed64,8,opt,name=p99_duration_ms,json=p99DurationMs,proto3" json:"p99_duration_ms"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) Reset() {
	*x = ResponseGetFeatureMetrics_FeatureMetric{}
	mi := &file_ontology_res_get_feature_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureMetrics_FeatureMetric) ProtoMessage() {}

func (x *ResponseGetFeatureMetrics_FeatureMetric) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureMetrics_FeatureMetric.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureMetrics_FeatureMetric) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_metrics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetWindowStart() string {
	if x != nil {
		return x.WindowStart
	}
	return ""
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetWindowMinutes() int32 {
	if x != nil {
		return x.WindowMinutes
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetFailureRate() float64 {
	if x != nil {
		return x.FailureRate
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetP50DurationMs() float64 {
	if x != nil {
		return x.P50DurationMs
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetP95DurationMs() float64 {
	if x != nil {
		return x.P95DurationMs
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetP99DurationMs() float64 {
	if x != nil {
		return x.P99DurationMs
	}
	return 0
}

func (x *ResponseGetFeatureMetrics_FeatureMetric) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_ontology_res_get_feature_metrics_proto protoreflect.FileDescriptor

const file_ontology_res_get_feature_metrics_proto_rawDesc = "" +
	"\n" +
	"&ontology/res_get_feature_metrics.proto\x12\x0etypes_ontology\"\xf4\x03\n" +
	"\x19ResponseGetFeatureMetrics\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12O\n" +
	"\x06result\x18\x03 \x01(\v27.types_ontology.ResponseGetFeatureMetrics.FeatureMetricR\x06result\x1a\xd7\x02\n" +
	"\rFeatureMetric\x12!\n" +
	"\fwindow_start\x18\x01 \x01(\tR\vwindowStart\x12%\n" +
	"\x0ewindow_minutes\x18\x02 \x01(\x05R\rwindowMinutes\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12!\n" +
	"\ffailure_rate\x18\x05 \x01(\x01R\vfailureRate\x12&\n" +
	"\x0fp50_duration_ms\x18\x06 \x01(\x01R\rp50DurationMs\x12&\n" +
	"\x0fp95_duration_ms\x18\a \x01(\x01R\rp95DurationMs\x12&\n" +
	"\x0fp99_duration_ms\x18\b \x01(\x01R\rp99DurationMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_feature_metrics_proto_rawDescOnce sync.Once
	file_ontology_res_get_feature_metrics_proto_rawDescData []byte
)

func file_ontology_res_get_feature_metrics_proto_rawDescGZIP() []byte {
	file_ontology_res_get_feature_metrics_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_feature_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_feature_metrics_proto_rawDesc), len(file_ontology_res_get_feature_metrics_proto_rawDesc)))
	})
	return file_ontology_res_get_feature_metrics_proto_rawDescData
}

var file_ontology_res_get_feature_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ontology_res_get_feature_metrics_proto_goTypes = []any{
	(*ResponseGetFeatureMetrics)(nil),               // 0: types_ontology.ResponseGetFeatureMetrics
	(*ResponseGetFeatureMetrics_FeatureMetric)(nil), // 1: types_ontology.ResponseGetFeatureMetrics.FeatureMetric
}
var file_ontology_res_get_feature_metrics_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetFeatureMetrics.result:type_name -> types_ontology.ResponseGetFeatureMetrics.FeatureMetric
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ontology_res_get_feature_metrics_proto_init() }
func file_ontology_res_get_feature_metrics_proto_init() {
	if File_ontology_res_get_feature_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_feature_metrics_proto_rawDesc), len(file_ontology_res_get_feature_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_feature_metrics_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_feature_metrics_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_feature_metrics_proto_msgTypes,
	}.Build()
	File_ontology_res_get_feature_metrics_proto = out.File
	file_ontology_res_get_feature_metrics_proto_goTypes = nil
	file_ontology_res_get_feature_metrics_proto_depIdxs = nil
}
