// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_services.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetServices struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          string                          `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data          []*ResponseGetServices_Service  `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pagination    *ResponseGetServices_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServices) Reset() {
	*x = ResponseGetServices{}
	mi := &file_ontology_res_get_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServices) ProtoMessage() {}

func (x *ResponseGetServices) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServices.ProtoReflect.Descriptor instead.
func (*ResponseGetServices) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_services_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetServices) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetServices) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetServices) GetData() []*ResponseGetServices_Service {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseGetServices) GetPagination() *ResponseGetServices_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetServices_Service struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	CriticalityLevel string                 `protobuf:"bytes,4,opt,name=criticality_level,json=criticalityLevel,proto3" json:"criticality_level"`
	UpdatedAt        string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	RepositoryUrl    string                 `protobuf:"bytes,6,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseGetServices_Service) Reset() {
	*x = ResponseGetServices_Service{}
	mi := &file_ontology_res_get_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServices_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServices_Service) ProtoMessage() {}

func (x *ResponseGetServices_Service) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServices_Service.ProtoReflect.Descriptor instead.
func (*ResponseGetServices_Service) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_services_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetServices_Service) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetServices_Service) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetServices_Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseGetServices_Service) GetCriticalityLevel() string {
	if x != nil {
		return x.CriticalityLevel
	}
	return ""
}

func (x *ResponseGetServices_Service) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ResponseGetServices_Service) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

type ResponseGetServices_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServices_Pagination) Reset() {
	*x = ResponseGetServices_Pagination{}
	mi := &file_ontology_res_get_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServices_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServices_Pagination) ProtoMessage() {}

func (x *ResponseGetServices_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServices_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetServices_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_services_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetServices_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetServices_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetServices_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetServices_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_services_proto protoreflect.FileDescriptor

const file_ontology_res_get_services_proto_rawDesc = "" +
	"\n" +
	"\x1fontology/res_get_services.proto\x12\x0etypes_ontology\"\x9c\x04\n" +
	"\x13ResponseGetServices\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x04data\x18\x03 \x03(\v2+.types_ontology.ResponseGetServices.ServiceR\x04data\x12N\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2..types_ontology.ResponseGetServices.PaginationR\n" +
	"pagination\x1a\xb4\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x11criticality_level\x18\x04 \x01(\tR\x10criticalityLevel\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12%\n" +
	"\x0erepository_url\x18\x06 \x01(\tR\rrepositoryUrl\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_services_proto_rawDescOnce sync.Once
	file_ontology_res_get_services_proto_rawDescData []byte
)

func file_ontology_res_get_services_proto_rawDescGZIP() []byte {
	file_ontology_res_get_services_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_services_proto_rawDesc), len(file_ontology_res_get_services_proto_rawDesc)))
	})
	return file_ontology_res_get_services_proto_rawDescData
}

var file_ontology_res_get_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_services_proto_goTypes = []any{
	(*ResponseGetServices)(nil),            // 0: types_ontology.ResponseGetServices
	(*ResponseGetServices_Service)(nil),    // 1: types_ontology.ResponseGetServices.Service
	(*ResponseGetServices_Pagination)(nil), // 2: types_ontology.ResponseGetServices.Pagination
}
var file_ontology_res_get_services_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetServices.data:type_name -> types_ontology.ResponseGetServices.Service
	2, // 1: types_ontology.ResponseGetServices.pagination:type_name -> types_ontology.ResponseGetServices.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_services_proto_init() }
func file_ontology_res_get_services_proto_init() {
	if File_ontology_res_get_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_services_proto_rawDesc), len(file_ontology_res_get_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_services_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_services_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_services_proto_msgTypes,
	}.Build()
	File_ontology_res_get_services_proto = out.File
	file_ontology_res_get_services_proto_goTypes = nil
	file_ontology_res_get_services_proto_depIdxs = nil
}
