// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_feature_instances.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetFeatureInstances struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Code          string                                         `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetFeatureInstances_FeatureInstance `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetFeatureInstances_Pagination        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatureInstances) Reset() {
	*x = ResponseGetFeatureInstances{}
	mi := &file_ontology_res_get_feature_instances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureInstances) ProtoMessage() {}

func (x *ResponseGetFeatureInstances) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_instances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureInstances.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureInstances) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_instances_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetFeatureInstances) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetFeatureInstances) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetFeatureInstances) GetResult() []*ResponseGetFeatureInstances_FeatureInstance {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetFeatureInstances) GetPagination() *ResponseGetFeatureInstances_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetFeatureInstances_FeatureInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	FeatureId     int64                  `protobuf:"varint,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	StartedAt     string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at"`
	CompletedAt   string                 `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatureInstances_FeatureInstance) Reset() {
	*x = ResponseGetFeatureInstances_FeatureInstance{}
	mi := &file_ontology_res_get_feature_instances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureInstances_FeatureInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureInstances_FeatureInstance) ProtoMessage() {}

func (x *ResponseGetFeatureInstances_FeatureInstance) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_instances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureInstances_FeatureInstance.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureInstances_FeatureInstance) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_instances_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetFeatureInstances_FeatureInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseGetFeatureInstances_FeatureInstance) GetFeatureId() int64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

func (x *ResponseGetFeatureInstances_FeatureInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResponseGetFeatureInstances_FeatureInstance) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ResponseGetFeatureInstances_FeatureInstance) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type ResponseGetFeatureInstances_Pagination struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextCursor     string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor"`
	PreviousCursor string                 `protobuf:"bytes,2,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor"`
	HasNext        bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next"`
	HasPrevious    bool                   `protobuf:"varint,4,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseGetFeatureInstances_Pagination) Reset() {
	*x = ResponseGetFeatureInstances_Pagination{}
	mi := &file_ontology_res_get_feature_instances_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureInstances_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureInstances_Pagination) ProtoMessage() {}

func (x *ResponseGetFeatureInstances_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_instances_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureInstances_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureInstances_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_instances_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetFeatureInstances_Pagination) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ResponseGetFeatureInstances_Pagination) GetPreviousCursor() string {
	if x != nil {
		return x.PreviousCursor
	}
	return ""
}

func (x *ResponseGetFeatureInstances_Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *ResponseGetFeatureInstances_Pagination) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *ResponseGetFeatureInstances_Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_ontology_res_get_feature_instances_proto protoreflect.FileDescriptor

const file_ontology_res_get_feature_instances_proto_rawDesc = "" +
	"\n" +
	"(ontology/res_get_feature_instances.proto\x12\x0etypes_ontology\"\xc2\x04\n" +
	"\x1bResponseGetFeatureInstances\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12S\n" +
	"\x06result\x18\x03 \x03(\v2;.types_ontology.ResponseGetFeatureInstances.FeatureInstanceR\x06result\x12V\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v26.types_ontology.ResponseGetFeatureInstances.PaginationR\n" +
	"pagination\x1a\x9a\x01\n" +
	"\x0fFeatureInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x02 \x01(\x03R\tfeatureId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\tR\vcompletedAt\x1a\xaa\x01\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12'\n" +
	"\x0fprevious_cursor\x18\x02 \x01(\tR\x0epreviousCursor\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x04 \x01(\bR\vhasPrevious\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_feature_instances_proto_rawDescOnce sync.Once
	file_ontology_res_get_feature_instances_proto_rawDescData []byte
)

func file_ontology_res_get_feature_instances_proto_rawDescGZIP() []byte {
	file_ontology_res_get_feature_instances_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_feature_instances_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_feature_instances_proto_rawDesc), len(file_ontology_res_get_feature_instances_proto_rawDesc)))
	})
	return file_ontology_res_get_feature_instances_proto_rawDescData
}

var file_ontology_res_get_feature_instances_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_feature_instances_proto_goTypes = []any{
	(*ResponseGetFeatureInstances)(nil),                 // 0: types_ontology.ResponseGetFeatureInstances
	(*ResponseGetFeatureInstances_FeatureInstance)(nil), // 1: types_ontology.ResponseGetFeatureInstances.FeatureInstance
	(*ResponseGetFeatureInstances_Pagination)(nil),      // 2: types_ontology.ResponseGetFeatureInstances.Pagination
}
var file_ontology_res_get_feature_instances_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetFeatureInstances.result:type_name -> types_ontology.ResponseGetFeatureInstances.FeatureInstance
	2, // 1: types_ontology.ResponseGetFeatureInstances.pagination:type_name -> types_ontology.ResponseGetFeatureInstances.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_feature_instances_proto_init() }
func file_ontology_res_get_feature_instances_proto_init() {
	if File_ontology_res_get_feature_instances_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_feature_instances_proto_rawDesc), len(file_ontology_res_get_feature_instances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_feature_instances_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_feature_instances_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_feature_instances_proto_msgTypes,
	}.Build()
	File_ontology_res_get_feature_instances_proto = out.File
	file_ontology_res_get_feature_instances_proto_goTypes = nil
	file_ontology_res_get_feature_instances_proto_depIdxs = nil
}
