// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_entity_transitions.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetEntityTransitions struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Code          string                                     `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetEntityTransitions_Transition `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetEntityTransitions) Reset() {
	*x = ResponseGetEntityTransitions{}
	mi := &file_ontology_res_get_entity_transitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntityTransitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntityTransitions) ProtoMessage() {}

func (x *ResponseGetEntityTransitions) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entity_transitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntityTransitions.ProtoReflect.Descriptor instead.
func (*ResponseGetEntityTransitions) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entity_transitions_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetEntityTransitions) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetEntityTransitions) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetEntityTransitions) GetResult() []*ResponseGetEntityTransitions_Transition {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseGetEntityTransitions_Transition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	FromEntityId         int64                  `protobuf:"varint,2,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id"`
	ToEntityId           int64                  `protobuf:"varint,3,opt,name=to_entity_id,json=toEntityId,proto3" json:"to_entity_id"`
	ConditionExpression  string                 `protobuf:"bytes,4,opt,name=condition_expression,json=conditionExpression,proto3" json:"condition_expression"`
	TransitionType       string                 `protobuf:"bytes,5,opt,name=transition_type,json=transitionType,proto3" json:"transition_type"`
	ConditionDescription string                 `protobuf:"bytes,6,opt,name=condition_description,json=conditionDescription,proto3" json:"condition_description"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResponseGetEntityTransitions_Transition) Reset() {
	*x = ResponseGetEntityTransitions_Transition{}
	mi := &file_ontology_res_get_entity_transitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntityTransitions_Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntityTransitions_Transition) ProtoMessage() {}

func (x *ResponseGetEntityTransitions_Transition) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entity_transitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntityTransitions_Transition.ProtoReflect.Descriptor instead.
func (*ResponseGetEntityTransitions_Transition) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entity_transitions_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetEntityTransitions_Transition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetEntityTransitions_Transition) GetFromEntityId() int64 {
	if x != nil {
		return x.FromEntityId
	}
	return 0
}

func (x *ResponseGetEntityTransitions_Transition) GetToEntityId() int64 {
	if x != nil {
		return x.ToEntityId
	}
	return 0
}

func (x *ResponseGetEntityTransitions_Transition) GetConditionExpression() string {
	if x != nil {
		return x.ConditionExpression
	}
	return ""
}

func (x *ResponseGetEntityTransitions_Transition) GetTransitionType() string {
	if x != nil {
		return x.TransitionType
	}
	return ""
}

func (x *ResponseGetEntityTransitions_Transition) GetConditionDescription() string {
	if x != nil {
		return x.ConditionDescription
	}
	return ""
}

var File_ontology_res_get_entity_transitions_proto protoreflect.FileDescriptor

const file_ontology_res_get_entity_transitions_proto_rawDesc = "" +
	"\n" +
	")ontology/res_get_entity_transitions.proto\x12\x0etypes_ontology\"\x95\x03\n" +
	"\x1cResponseGetEntityTransitions\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12O\n" +
	"\x06result\x18\x03 \x03(\v27.types_ontology.ResponseGetEntityTransitions.TransitionR\x06result\x1a\xf5\x01\n" +
	"\n" +
	"Transition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x0efrom_entity_id\x18\x02 \x01(\x03R\ffromEntityId\x12 \n" +
	"\fto_entity_id\x18\x03 \x01(\x03R\n" +
	"toEntityId\x121\n" +
	"\x14condition_expression\x18\x04 \x01(\tR\x13conditionExpression\x12'\n" +
	"\x0ftransition_type\x18\x05 \x01(\tR\x0etransitionType\x123\n" +
	"\x15condition_description\x18\x06 \x01(\tR\x14conditionDescriptionB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_entity_transitions_proto_rawDescOnce sync.Once
	file_ontology_res_get_entity_transitions_proto_rawDescData []byte
)

func file_ontology_res_get_entity_transitions_proto_rawDescGZIP() []byte {
	file_ontology_res_get_entity_transitions_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_entity_transitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_entity_transitions_proto_rawDesc), len(file_ontology_res_get_entity_transitions_proto_rawDesc)))
	})
	return file_ontology_res_get_entity_transitions_proto_rawDescData
}

var file_ontology_res_get_entity_transitions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ontology_res_get_entity_transitions_proto_goTypes = []any{
	(*ResponseGetEntityTransitions)(nil),            // 0: types_ontology.ResponseGetEntityTransitions
	(*ResponseGetEntityTransitions_Transition)(nil), // 1: types_ontology.ResponseGetEntityTransitions.Transition
}
var file_ontology_res_get_entity_transitions_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetEntityTransitions.result:type_name -> types_ontology.ResponseGetEntityTransitions.Transition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ontology_res_get_entity_transitions_proto_init() }
func file_ontology_res_get_entity_transitions_proto_init() {
	if File_ontology_res_get_entity_transitions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_entity_transitions_proto_rawDesc), len(file_ontology_res_get_entity_transitions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_entity_transitions_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_entity_transitions_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_entity_transitions_proto_msgTypes,
	}.Build()
	File_ontology_res_get_entity_transitions_proto = out.File
	file_ontology_res_get_entity_transitions_proto_goTypes = nil
	file_ontology_res_get_entity_transitions_proto_depIdxs = nil
}
