// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_teams.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetTeams struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          string                       `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetTeams_Team     `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetTeams_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetTeams) Reset() {
	*x = ResponseGetTeams{}
	mi := &file_ontology_res_get_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetTeams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetTeams) ProtoMessage() {}

func (x *ResponseGetTeams) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetTeams.ProtoReflect.Descriptor instead.
func (*ResponseGetTeams) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_teams_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetTeams) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetTeams) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetTeams) GetResult() []*ResponseGetTeams_Team {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetTeams) GetPagination() *ResponseGetTeams_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetTeams_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	SlackChannel  string                 `protobuf:"bytes,3,opt,name=slack_channel,json=slackChannel,proto3" json:"slack_channel"`
	OncallEmail   string                 `protobuf:"bytes,4,opt,name=oncall_email,json=oncallEmail,proto3" json:"oncall_email"`
	RoleName      string                 `protobuf:"bytes,5,opt,name=role_name,json=roleName,proto3" json:"role_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetTeams_Team) Reset() {
	*x = ResponseGetTeams_Team{}
	mi := &file_ontology_res_get_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetTeams_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetTeams_Team) ProtoMessage() {}

func (x *ResponseGetTeams_Team) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetTeams_Team.ProtoReflect.Descriptor instead.
func (*ResponseGetTeams_Team) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_teams_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetTeams_Team) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetTeams_Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseGetTeams_Team) GetSlackChannel() string {
	if x != nil {
		return x.SlackChannel
	}
	return ""
}

func (x *ResponseGetTeams_Team) GetOncallEmail() string {
	if x != nil {
		return x.OncallEmail
	}
	return ""
}

func (x *ResponseGetTeams_Team) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type ResponseGetTeams_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetTeams_Pagination) Reset() {
	*x = ResponseGetTeams_Pagination{}
	mi := &file_ontology_res_get_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetTeams_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetTeams_Pagination) ProtoMessage() {}

func (x *ResponseGetTeams_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetTeams_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetTeams_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_teams_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetTeams_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetTeams_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetTeams_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetTeams_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_teams_proto protoreflect.FileDescriptor

const file_ontology_res_get_teams_proto_rawDesc = "" +
	"\n" +
	"\x1contology/res_get_teams.proto\x12\x0etypes_ontology\"\xef\x03\n" +
	"\x10ResponseGetTeams\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x06result\x18\x03 \x03(\v2%.types_ontology.ResponseGetTeams.TeamR\x06result\x12K\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2+.types_ontology.ResponseGetTeams.PaginationR\n" +
	"pagination\x1a\x8f\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rslack_channel\x18\x03 \x01(\tR\fslackChannel\x12!\n" +
	"\foncall_email\x18\x04 \x01(\tR\voncallEmail\x12\x1b\n" +
	"\trole_name\x18\x05 \x01(\tR\broleName\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_teams_proto_rawDescOnce sync.Once
	file_ontology_res_get_teams_proto_rawDescData []byte
)

func file_ontology_res_get_teams_proto_rawDescGZIP() []byte {
	file_ontology_res_get_teams_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_teams_proto_rawDesc), len(file_ontology_res_get_teams_proto_rawDesc)))
	})
	return file_ontology_res_get_teams_proto_rawDescData
}

var file_ontology_res_get_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_teams_proto_goTypes = []any{
	(*ResponseGetTeams)(nil),            // 0: types_ontology.ResponseGetTeams
	(*ResponseGetTeams_Team)(nil),       // 1: types_ontology.ResponseGetTeams.Team
	(*ResponseGetTeams_Pagination)(nil), // 2: types_ontology.ResponseGetTeams.Pagination
}
var file_ontology_res_get_teams_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetTeams.result:type_name -> types_ontology.ResponseGetTeams.Team
	2, // 1: types_ontology.ResponseGetTeams.pagination:type_name -> types_ontology.ResponseGetTeams.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_teams_proto_init() }
func file_ontology_res_get_teams_proto_init() {
	if File_ontology_res_get_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_teams_proto_rawDesc), len(file_ontology_res_get_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_teams_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_teams_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_teams_proto_msgTypes,
	}.Build()
	File_ontology_res_get_teams_proto = out.File
	file_ontology_res_get_teams_proto_goTypes = nil
	file_ontology_res_get_teams_proto_depIdxs = nil
}
