// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_features.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetFeatures struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          string                          `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetFeatures_Feature  `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetFeatures_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatures) Reset() {
	*x = ResponseGetFeatures{}
	mi := &file_ontology_res_get_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatures) ProtoMessage() {}

func (x *ResponseGetFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatures.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatures) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_features_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetFeatures) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetFeatures) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetFeatures) GetResult() []*ResponseGetFeatures_Feature {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetFeatures) GetPagination() *ResponseGetFeatures_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetFeatures_Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatures_Feature) Reset() {
	*x = ResponseGetFeatures_Feature{}
	mi := &file_ontology_res_get_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatures_Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatures_Feature) ProtoMessage() {}

func (x *ResponseGetFeatures_Feature) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatures_Feature.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatures_Feature) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_features_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetFeatures_Feature) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetFeatures_Feature) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetFeatures_Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseGetFeatures_Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseGetFeatures_Feature) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ResponseGetFeatures_Feature) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseGetFeatures_Feature) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResponseGetFeatures_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatures_Pagination) Reset() {
	*x = ResponseGetFeatures_Pagination{}
	mi := &file_ontology_res_get_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatures_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatures_Pagination) ProtoMessage() {}

func (x *ResponseGetFeatures_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatures_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatures_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_features_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetFeatures_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetFeatures_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetFeatures_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetFeatures_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_features_proto protoreflect.FileDescriptor

const file_ontology_res_get_features_proto_rawDesc = "" +
	"\n" +
	"\x1fontology/res_get_features.proto\x12\x0etypes_ontology\"\xaa\x04\n" +
	"\x13ResponseGetFeatures\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x03 \x03(\v2+.types_ontology.ResponseGetFeatures.FeatureR\x06result\x12N\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2..types_ontology.ResponseGetFeatures.PaginationR\n" +
	"pagination\x1a\xbe\x01\n" +
	"\aFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_features_proto_rawDescOnce sync.Once
	file_ontology_res_get_features_proto_rawDescData []byte
)

func file_ontology_res_get_features_proto_rawDescGZIP() []byte {
	file_ontology_res_get_features_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_features_proto_rawDesc), len(file_ontology_res_get_features_proto_rawDesc)))
	})
	return file_ontology_res_get_features_proto_rawDescData
}

var file_ontology_res_get_features_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_features_proto_goTypes = []any{
	(*ResponseGetFeatures)(nil),            // 0: types_ontology.ResponseGetFeatures
	(*ResponseGetFeatures_Feature)(nil),    // 1: types_ontology.ResponseGetFeatures.Feature
	(*ResponseGetFeatures_Pagination)(nil), // 2: types_ontology.ResponseGetFeatures.Pagination
}
var file_ontology_res_get_features_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetFeatures.result:type_name -> types_ontology.ResponseGetFeatures.Feature
	2, // 1: types_ontology.ResponseGetFeatures.pagination:type_name -> types_ontology.ResponseGetFeatures.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_features_proto_init() }
func file_ontology_res_get_features_proto_init() {
	if File_ontology_res_get_features_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_features_proto_rawDesc), len(file_ontology_res_get_features_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_features_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_features_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_features_proto_msgTypes,
	}.Build()
	File_ontology_res_get_features_proto = out.File
	file_ontology_res_get_features_proto_goTypes = nil
	file_ontology_res_get_features_proto_depIdxs = nil
}
