// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_create_entity.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCreateEntity struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          string                       `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        *ResponseCreateEntity_Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateEntity) Reset() {
	*x = ResponseCreateEntity{}
	mi := &file_ontology_res_create_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateEntity) ProtoMessage() {}

func (x *ResponseCreateEntity) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_create_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateEntity.ProtoReflect.Descriptor instead.
func (*ResponseCreateEntity) Descriptor() ([]byte, []int) {
	return file_ontology_res_create_entity_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseCreateEntity) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseCreateEntity) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseCreateEntity) GetResult() *ResponseCreateEntity_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseCreateEntity_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	FeatureId     int64                  `protobuf:"varint,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	DisplayOrder  int32                  `protobuf:"varint,6,opt,name=display_order,json=displayOrder,proto3" json:"display_order"`
	IsStart       bool                   `protobuf:"varint,7,opt,name=is_start,json=isStart,proto3" json:"is_start"`
	IsTerminal    bool                   `protobuf:"varint,8,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateEntity_Result) Reset() {
	*x = ResponseCreateEntity_Result{}
	mi := &file_ontology_res_create_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateEntity_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateEntity_Result) ProtoMessage() {}

func (x *ResponseCreateEntity_Result) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_create_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateEntity_Result.ProtoReflect.Descriptor instead.
func (*ResponseCreateEntity_Result) Descriptor() ([]byte, []int) {
	return file_ontology_res_create_entity_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseCreateEntity_Result) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseCreateEntity_Result) GetFeatureId() int64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

func (x *ResponseCreateEntity_Result) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseCreateEntity_Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseCreateEntity_Result) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseCreateEntity_Result) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *ResponseCreateEntity_Result) GetIsStart() bool {
	if x != nil {
		return x.IsStart
	}
	return false
}

func (x *ResponseCreateEntity_Result) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *ResponseCreateEntity_Result) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseCreateEntity_Result) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_ontology_res_create_entity_proto protoreflect.FileDescriptor

const file_ontology_res_create_entity_proto_rawDesc = "" +
	"\n" +
	" ontology/res_create_entity.proto\x12\x0etypes_ontology\"\xac\x03\n" +
	"\x14ResponseCreateEntity\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x03 \x01(\v2+.types_ontology.ResponseCreateEntity.ResultR\x06result\x1a\xa0\x02\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x02 \x01(\x03R\tfeatureId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rdisplay_order\x18\x06 \x01(\x05R\fdisplayOrder\x12\x19\n" +
	"\bis_start\x18\a \x01(\bR\aisStart\x12\x1f\n" +
	"\vis_terminal\x18\b \x01(\bR\n" +
	"isTerminal\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAtB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_create_entity_proto_rawDescOnce sync.Once
	file_ontology_res_create_entity_proto_rawDescData []byte
)

func file_ontology_res_create_entity_proto_rawDescGZIP() []byte {
	file_ontology_res_create_entity_proto_rawDescOnce.Do(func() {
		file_ontology_res_create_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_create_entity_proto_rawDesc), len(file_ontology_res_create_entity_proto_rawDesc)))
	})
	return file_ontology_res_create_entity_proto_rawDescData
}

var file_ontology_res_create_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ontology_res_create_entity_proto_goTypes = []any{
	(*ResponseCreateEntity)(nil),        // 0: types_ontology.ResponseCreateEntity
	(*ResponseCreateEntity_Result)(nil), // 1: types_ontology.ResponseCreateEntity.Result
}
var file_ontology_res_create_entity_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseCreateEntity.result:type_name -> types_ontology.ResponseCreateEntity.Result
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ontology_res_create_entity_proto_init() }
func file_ontology_res_create_entity_proto_init() {
	if File_ontology_res_create_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_create_entity_proto_rawDesc), len(file_ontology_res_create_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_create_entity_proto_goTypes,
		DependencyIndexes: file_ontology_res_create_entity_proto_depIdxs,
		MessageInfos:      file_ontology_res_create_entity_proto_msgTypes,
	}.Build()
	File_ontology_res_create_entity_proto = out.File
	file_ontology_res_create_entity_proto_goTypes = nil
	file_ontology_res_create_entity_proto_depIdxs = nil
}
