// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_entities.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetEntities struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          string                          `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data          []*ResponseGetEntities_Entity   `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pagination    *ResponseGetEntities_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetEntities) Reset() {
	*x = ResponseGetEntities{}
	mi := &file_ontology_res_get_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntities) ProtoMessage() {}

func (x *ResponseGetEntities) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntities.ProtoReflect.Descriptor instead.
func (*ResponseGetEntities) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entities_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetEntities) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetEntities) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetEntities) GetData() []*ResponseGetEntities_Entity {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseGetEntities) GetPagination() *ResponseGetEntities_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetEntities_Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	FeatureId     int64                  `protobuf:"varint,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	DisplayOrder  int32                  `protobuf:"varint,5,opt,name=display_order,json=displayOrder,proto3" json:"display_order"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	IsStart       bool                   `protobuf:"varint,7,opt,name=is_start,json=isStart,proto3" json:"is_start"`
	IsTerminal    bool                   `protobuf:"varint,8,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetEntities_Entity) Reset() {
	*x = ResponseGetEntities_Entity{}
	mi := &file_ontology_res_get_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntities_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntities_Entity) ProtoMessage() {}

func (x *ResponseGetEntities_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntities_Entity.ProtoReflect.Descriptor instead.
func (*ResponseGetEntities_Entity) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entities_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetEntities_Entity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetEntities_Entity) GetFeatureId() int64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

func (x *ResponseGetEntities_Entity) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetEntities_Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseGetEntities_Entity) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *ResponseGetEntities_Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseGetEntities_Entity) GetIsStart() bool {
	if x != nil {
		return x.IsStart
	}
	return false
}

func (x *ResponseGetEntities_Entity) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *ResponseGetEntities_Entity) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseGetEntities_Entity) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResponseGetEntities_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetEntities_Pagination) Reset() {
	*x = ResponseGetEntities_Pagination{}
	mi := &file_ontology_res_get_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntities_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntities_Pagination) ProtoMessage() {}

func (x *ResponseGetEntities_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntities_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetEntities_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entities_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetEntities_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetEntities_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetEntities_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetEntities_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_entities_proto protoreflect.FileDescriptor

const file_ontology_res_get_entities_proto_rawDesc = "" +
	"\n" +
	"\x1fontology/res_get_entities.proto\x12\x0etypes_ontology\"\x87\x05\n" +
	"\x13ResponseGetEntities\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x03(\v2*.types_ontology.ResponseGetEntities.EntityR\x04data\x12N\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2..types_ontology.ResponseGetEntities.PaginationR\n" +
	"pagination\x1a\xa0\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x02 \x01(\x03R\tfeatureId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rdisplay_order\x18\x05 \x01(\x05R\fdisplayOrder\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x19\n" +
	"\bis_start\x18\a \x01(\bR\aisStart\x12\x1f\n" +
	"\vis_terminal\x18\b \x01(\bR\n" +
	"isTerminal\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_entities_proto_rawDescOnce sync.Once
	file_ontology_res_get_entities_proto_rawDescData []byte
)

func file_ontology_res_get_entities_proto_rawDescGZIP() []byte {
	file_ontology_res_get_entities_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_entities_proto_rawDesc), len(file_ontology_res_get_entities_proto_rawDesc)))
	})
	return file_ontology_res_get_entities_proto_rawDescData
}

var file_ontology_res_get_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_entities_proto_goTypes = []any{
	(*ResponseGetEntities)(nil),            // 0: types_ontology.ResponseGetEntities
	(*ResponseGetEntities_Entity)(nil),     // 1: types_ontology.ResponseGetEntities.Entity
	(*ResponseGetEntities_Pagination)(nil), // 2: types_ontology.ResponseGetEntities.Pagination
}
var file_ontology_res_get_entities_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetEntities.data:type_name -> types_ontology.ResponseGetEntities.Entity
	2, // 1: types_ontology.ResponseGetEntities.pagination:type_name -> types_ontology.ResponseGetEntities.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_entities_proto_init() }
func file_ontology_res_get_entities_proto_init() {
	if File_ontology_res_get_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_entities_proto_rawDesc), len(file_ontology_res_get_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_entities_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_entities_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_entities_proto_msgTypes,
	}.Build()
	File_ontology_res_get_entities_proto = out.File
	file_ontology_res_get_entities_proto_goTypes = nil
	file_ontology_res_get_entities_proto_depIdxs = nil
}
