// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_entity_metrics.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetEntityMetrics struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Code          string                               `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                               `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetEntityMetrics_Metric   `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetEntityMetrics_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetEntityMetrics) Reset() {
	*x = ResponseGetEntityMetrics{}
	mi := &file_ontology_res_get_entity_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntityMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntityMetrics) ProtoMessage() {}

func (x *ResponseGetEntityMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entity_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntityMetrics.ProtoReflect.Descriptor instead.
func (*ResponseGetEntityMetrics) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entity_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetEntityMetrics) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetEntityMetrics) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetEntityMetrics) GetResult() []*ResponseGetEntityMetrics_Metric {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetEntityMetrics) GetPagination() *ResponseGetEntityMetrics_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetEntityMetrics_Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowStart   string                 `protobuf:"bytes,1,opt,name=window_start,json=windowStart,proto3" json:"window_start"`
	WindowMinutes int32                  `protobuf:"varint,2,opt,name=window_minutes,json=windowMinutes,proto3" json:"window_minutes"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	SuccessRate   float32                `protobuf:"fixed32,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate"`
	FailureRate   float32                `protobuf:"fixed32,5,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate"`
	P50DurationMs float32                `protobuf:"fixed32,6,opt,name=p50_duration_ms,json=p50DurationMs,proto3" json:"p50_duration_ms"`
	P95DurationMs float32                `protobuf:"fixed32,7,opt,name=p95_duration_ms,json=p95DurationMs,proto3" json:"p95_duration_ms"`
	P99DurationMs float32                `protobuf:"fixed32,8,opt,name=p99_duration_ms,json=p99DurationMs,proto3" json:"p99_duration_ms"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetEntityMetrics_Metric) Reset() {
	*x = ResponseGetEntityMetrics_Metric{}
	mi := &file_ontology_res_get_entity_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntityMetrics_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntityMetrics_Metric) ProtoMessage() {}

func (x *ResponseGetEntityMetrics_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entity_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntityMetrics_Metric.ProtoReflect.Descriptor instead.
func (*ResponseGetEntityMetrics_Metric) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entity_metrics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetEntityMetrics_Metric) GetWindowStart() string {
	if x != nil {
		return x.WindowStart
	}
	return ""
}

func (x *ResponseGetEntityMetrics_Metric) GetWindowMinutes() int32 {
	if x != nil {
		return x.WindowMinutes
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetSuccessRate() float32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetFailureRate() float32 {
	if x != nil {
		return x.FailureRate
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetP50DurationMs() float32 {
	if x != nil {
		return x.P50DurationMs
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetP95DurationMs() float32 {
	if x != nil {
		return x.P95DurationMs
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetP99DurationMs() float32 {
	if x != nil {
		return x.P99DurationMs
	}
	return 0
}

func (x *ResponseGetEntityMetrics_Metric) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ResponseGetEntityMetrics_Pagination struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextCursor     string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor"`
	PreviousCursor string                 `protobuf:"bytes,2,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor"`
	HasNext        bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next"`
	HasPrevious    bool                   `protobuf:"varint,4,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseGetEntityMetrics_Pagination) Reset() {
	*x = ResponseGetEntityMetrics_Pagination{}
	mi := &file_ontology_res_get_entity_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetEntityMetrics_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetEntityMetrics_Pagination) ProtoMessage() {}

func (x *ResponseGetEntityMetrics_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_entity_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetEntityMetrics_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetEntityMetrics_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_entity_metrics_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetEntityMetrics_Pagination) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ResponseGetEntityMetrics_Pagination) GetPreviousCursor() string {
	if x != nil {
		return x.PreviousCursor
	}
	return ""
}

func (x *ResponseGetEntityMetrics_Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *ResponseGetEntityMetrics_Pagination) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *ResponseGetEntityMetrics_Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_ontology_res_get_entity_metrics_proto protoreflect.FileDescriptor

const file_ontology_res_get_entity_metrics_proto_rawDesc = "" +
	"\n" +
	"%ontology/res_get_entity_metrics.proto\x12\x0etypes_ontology\"\xe6\x05\n" +
	"\x18ResponseGetEntityMetrics\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x06result\x18\x03 \x03(\v2/.types_ontology.ResponseGetEntityMetrics.MetricR\x06result\x12S\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v23.types_ontology.ResponseGetEntityMetrics.PaginationR\n" +
	"pagination\x1a\xd0\x02\n" +
	"\x06Metric\x12!\n" +
	"\fwindow_start\x18\x01 \x01(\tR\vwindowStart\x12%\n" +
	"\x0ewindow_minutes\x18\x02 \x01(\x05R\rwindowMinutes\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x02R\vsuccessRate\x12!\n" +
	"\ffailure_rate\x18\x05 \x01(\x02R\vfailureRate\x12&\n" +
	"\x0fp50_duration_ms\x18\x06 \x01(\x02R\rp50DurationMs\x12&\n" +
	"\x0fp95_duration_ms\x18\a \x01(\x02R\rp95DurationMs\x12&\n" +
	"\x0fp99_duration_ms\x18\b \x01(\x02R\rp99DurationMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x1a\xaa\x01\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12'\n" +
	"\x0fprevious_cursor\x18\x02 \x01(\tR\x0epreviousCursor\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x04 \x01(\bR\vhasPrevious\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_entity_metrics_proto_rawDescOnce sync.Once
	file_ontology_res_get_entity_metrics_proto_rawDescData []byte
)

func file_ontology_res_get_entity_metrics_proto_rawDescGZIP() []byte {
	file_ontology_res_get_entity_metrics_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_entity_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_entity_metrics_proto_rawDesc), len(file_ontology_res_get_entity_metrics_proto_rawDesc)))
	})
	return file_ontology_res_get_entity_metrics_proto_rawDescData
}

var file_ontology_res_get_entity_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_entity_metrics_proto_goTypes = []any{
	(*ResponseGetEntityMetrics)(nil),            // 0: types_ontology.ResponseGetEntityMetrics
	(*ResponseGetEntityMetrics_Metric)(nil),     // 1: types_ontology.ResponseGetEntityMetrics.Metric
	(*ResponseGetEntityMetrics_Pagination)(nil), // 2: types_ontology.ResponseGetEntityMetrics.Pagination
}
var file_ontology_res_get_entity_metrics_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetEntityMetrics.result:type_name -> types_ontology.ResponseGetEntityMetrics.Metric
	2, // 1: types_ontology.ResponseGetEntityMetrics.pagination:type_name -> types_ontology.ResponseGetEntityMetrics.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_entity_metrics_proto_init() }
func file_ontology_res_get_entity_metrics_proto_init() {
	if File_ontology_res_get_entity_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_entity_metrics_proto_rawDesc), len(file_ontology_res_get_entity_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_entity_metrics_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_entity_metrics_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_entity_metrics_proto_msgTypes,
	}.Build()
	File_ontology_res_get_entity_metrics_proto = out.File
	file_ontology_res_get_entity_metrics_proto_goTypes = nil
	file_ontology_res_get_entity_metrics_proto_depIdxs = nil
}
