// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ontology/res_get_kpis.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetKpis struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          string                      `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetKpis_Kpi      `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetKpis_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetKpis) Reset() {
	*x = ResponseGetKpis{}
	mi := &file_ontology_res_get_kpis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetKpis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetKpis) ProtoMessage() {}

func (x *ResponseGetKpis) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_kpis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetKpis.ProtoReflect.Descriptor instead.
func (*ResponseGetKpis) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_kpis_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetKpis) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetKpis) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetKpis) GetResult() []*ResponseGetKpis_Kpi {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetKpis) GetPagination() *ResponseGetKpis_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetKpis_Kpi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	MetricType    string                 `protobuf:"bytes,5,opt,name=metric_type,json=metricType,proto3" json:"metric_type"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetKpis_Kpi) Reset() {
	*x = ResponseGetKpis_Kpi{}
	mi := &file_ontology_res_get_kpis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetKpis_Kpi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetKpis_Kpi) ProtoMessage() {}

func (x *ResponseGetKpis_Kpi) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_kpis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetKpis_Kpi.ProtoReflect.Descriptor instead.
func (*ResponseGetKpis_Kpi) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_kpis_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetKpis_Kpi) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetKpis_Kpi) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetKpis_Kpi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseGetKpis_Kpi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseGetKpis_Kpi) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *ResponseGetKpis_Kpi) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ResponseGetKpis_Kpi) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseGetKpis_Kpi) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResponseGetKpis_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetKpis_Pagination) Reset() {
	*x = ResponseGetKpis_Pagination{}
	mi := &file_ontology_res_get_kpis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetKpis_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetKpis_Pagination) ProtoMessage() {}

func (x *ResponseGetKpis_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_kpis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetKpis_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetKpis_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_kpis_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetKpis_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetKpis_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetKpis_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetKpis_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_kpis_proto protoreflect.FileDescriptor

const file_ontology_res_get_kpis_proto_rawDesc = "" +
	"\n" +
	"\x1bontology/res_get_kpis.proto\x12\x0etypes_ontology\"\xae\x04\n" +
	"\x0fResponseGetKpis\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x06result\x18\x03 \x03(\v2#.types_ontology.ResponseGetKpis.KpiR\x06result\x12J\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2*.types_ontology.ResponseGetKpis.PaginationR\n" +
	"pagination\x1a\xd2\x01\n" +
	"\x03Kpi\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vmetric_type\x18\x05 \x01(\tR\n" +
	"metricType\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_kpis_proto_rawDescOnce sync.Once
	file_ontology_res_get_kpis_proto_rawDescData []byte
)

func file_ontology_res_get_kpis_proto_rawDescGZIP() []byte {
	file_ontology_res_get_kpis_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_kpis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_kpis_proto_rawDesc), len(file_ontology_res_get_kpis_proto_rawDesc)))
	})
	return file_ontology_res_get_kpis_proto_rawDescData
}

var file_ontology_res_get_kpis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_kpis_proto_goTypes = []any{
	(*ResponseGetKpis)(nil),            // 0: types_ontology.ResponseGetKpis
	(*ResponseGetKpis_Kpi)(nil),        // 1: types_ontology.ResponseGetKpis.Kpi
	(*ResponseGetKpis_Pagination)(nil), // 2: types_ontology.ResponseGetKpis.Pagination
}
var file_ontology_res_get_kpis_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetKpis.result:type_name -> types_ontology.ResponseGetKpis.Kpi
	2, // 1: types_ontology.ResponseGetKpis.pagination:type_name -> types_ontology.ResponseGetKpis.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_kpis_proto_init() }
func file_ontology_res_get_kpis_proto_init() {
	if File_ontology_res_get_kpis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_kpis_proto_rawDesc), len(file_ontology_res_get_kpis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_kpis_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_kpis_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_kpis_proto_msgTypes,
	}.Build()
	File_ontology_res_get_kpis_proto = out.File
	file_ontology_res_get_kpis_proto_goTypes = nil
	file_ontology_res_get_kpis_proto_depIdxs = nil
}
