// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_feature_teams.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetFeatureTeams struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          string                          `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetFeatureTeams_Team `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatureTeams) Reset() {
	*x = ResponseGetFeatureTeams{}
	mi := &file_ontology_res_get_feature_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureTeams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureTeams) ProtoMessage() {}

func (x *ResponseGetFeatureTeams) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureTeams.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureTeams) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_teams_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetFeatureTeams) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetFeatureTeams) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetFeatureTeams) GetResult() []*ResponseGetFeatureTeams_Team {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseGetFeatureTeams_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id"`
	TeamName      string                 `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetFeatureTeams_Team) Reset() {
	*x = ResponseGetFeatureTeams_Team{}
	mi := &file_ontology_res_get_feature_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetFeatureTeams_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetFeatureTeams_Team) ProtoMessage() {}

func (x *ResponseGetFeatureTeams_Team) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_feature_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetFeatureTeams_Team.ProtoReflect.Descriptor instead.
func (*ResponseGetFeatureTeams_Team) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_feature_teams_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetFeatureTeams_Team) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ResponseGetFeatureTeams_Team) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *ResponseGetFeatureTeams_Team) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

var File_ontology_res_get_feature_teams_proto protoreflect.FileDescriptor

const file_ontology_res_get_feature_teams_proto_rawDesc = "" +
	"\n" +
	"$ontology/res_get_feature_teams.proto\x12\x0etypes_ontology\"\xe8\x01\n" +
	"\x17ResponseGetFeatureTeams\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x06result\x18\x03 \x03(\v2,.types_ontology.ResponseGetFeatureTeams.TeamR\x06result\x1aY\n" +
	"\x04Team\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x02 \x01(\tR\bteamName\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleNameB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_feature_teams_proto_rawDescOnce sync.Once
	file_ontology_res_get_feature_teams_proto_rawDescData []byte
)

func file_ontology_res_get_feature_teams_proto_rawDescGZIP() []byte {
	file_ontology_res_get_feature_teams_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_feature_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_feature_teams_proto_rawDesc), len(file_ontology_res_get_feature_teams_proto_rawDesc)))
	})
	return file_ontology_res_get_feature_teams_proto_rawDescData
}

var file_ontology_res_get_feature_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ontology_res_get_feature_teams_proto_goTypes = []any{
	(*ResponseGetFeatureTeams)(nil),      // 0: types_ontology.ResponseGetFeatureTeams
	(*ResponseGetFeatureTeams_Team)(nil), // 1: types_ontology.ResponseGetFeatureTeams.Team
}
var file_ontology_res_get_feature_teams_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetFeatureTeams.result:type_name -> types_ontology.ResponseGetFeatureTeams.Team
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ontology_res_get_feature_teams_proto_init() }
func file_ontology_res_get_feature_teams_proto_init() {
	if File_ontology_res_get_feature_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_feature_teams_proto_rawDesc), len(file_ontology_res_get_feature_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_feature_teams_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_feature_teams_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_feature_teams_proto_msgTypes,
	}.Build()
	File_ontology_res_get_feature_teams_proto = out.File
	file_ontology_res_get_feature_teams_proto_goTypes = nil
	file_ontology_res_get_feature_teams_proto_depIdxs = nil
}
