// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_service_apis.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetServiceApis struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Code          string                             `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data          []*ResponseGetServiceApis_Api      `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pagination    *ResponseGetServiceApis_Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServiceApis) Reset() {
	*x = ResponseGetServiceApis{}
	mi := &file_ontology_res_get_service_apis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServiceApis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServiceApis) ProtoMessage() {}

func (x *ResponseGetServiceApis) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_service_apis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServiceApis.ProtoReflect.Descriptor instead.
func (*ResponseGetServiceApis) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_service_apis_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetServiceApis) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetServiceApis) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetServiceApis) GetData() []*ResponseGetServiceApis_Api {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseGetServiceApis) GetPagination() *ResponseGetServiceApis_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetServiceApis_Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint"`
	HttpMethod    string                 `protobuf:"bytes,3,opt,name=http_method,json=httpMethod,proto3" json:"http_method"`
	IsInternal    bool                   `protobuf:"varint,4,opt,name=is_internal,json=isInternal,proto3" json:"is_internal"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServiceApis_Api) Reset() {
	*x = ResponseGetServiceApis_Api{}
	mi := &file_ontology_res_get_service_apis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServiceApis_Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServiceApis_Api) ProtoMessage() {}

func (x *ResponseGetServiceApis_Api) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_service_apis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServiceApis_Api.ProtoReflect.Descriptor instead.
func (*ResponseGetServiceApis_Api) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_service_apis_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetServiceApis_Api) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetServiceApis_Api) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ResponseGetServiceApis_Api) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ResponseGetServiceApis_Api) GetIsInternal() bool {
	if x != nil {
		return x.IsInternal
	}
	return false
}

func (x *ResponseGetServiceApis_Api) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResponseGetServiceApis_Api) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResponseGetServiceApis_Api) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ResponseGetServiceApis_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServiceApis_Pagination) Reset() {
	*x = ResponseGetServiceApis_Pagination{}
	mi := &file_ontology_res_get_service_apis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServiceApis_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServiceApis_Pagination) ProtoMessage() {}

func (x *ResponseGetServiceApis_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_service_apis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServiceApis_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetServiceApis_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_service_apis_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetServiceApis_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetServiceApis_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetServiceApis_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetServiceApis_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_service_apis_proto protoreflect.FileDescriptor

const file_ontology_res_get_service_apis_proto_rawDesc = "" +
	"\n" +
	"#ontology/res_get_service_apis.proto\x12\x0etypes_ontology\"\xbb\x04\n" +
	"\x16ResponseGetServiceApis\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x03(\v2*.types_ontology.ResponseGetServiceApis.ApiR\x04data\x12Q\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v21.types_ontology.ResponseGetServiceApis.PaginationR\n" +
	"pagination\x1a\xce\x01\n" +
	"\x03Api\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vhttp_method\x18\x03 \x01(\tR\n" +
	"httpMethod\x12\x1f\n" +
	"\vis_internal\x18\x04 \x01(\bR\n" +
	"isInternal\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_service_apis_proto_rawDescOnce sync.Once
	file_ontology_res_get_service_apis_proto_rawDescData []byte
)

func file_ontology_res_get_service_apis_proto_rawDescGZIP() []byte {
	file_ontology_res_get_service_apis_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_service_apis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_service_apis_proto_rawDesc), len(file_ontology_res_get_service_apis_proto_rawDesc)))
	})
	return file_ontology_res_get_service_apis_proto_rawDescData
}

var file_ontology_res_get_service_apis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_service_apis_proto_goTypes = []any{
	(*ResponseGetServiceApis)(nil),            // 0: types_ontology.ResponseGetServiceApis
	(*ResponseGetServiceApis_Api)(nil),        // 1: types_ontology.ResponseGetServiceApis.Api
	(*ResponseGetServiceApis_Pagination)(nil), // 2: types_ontology.ResponseGetServiceApis.Pagination
}
var file_ontology_res_get_service_apis_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetServiceApis.data:type_name -> types_ontology.ResponseGetServiceApis.Api
	2, // 1: types_ontology.ResponseGetServiceApis.pagination:type_name -> types_ontology.ResponseGetServiceApis.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_service_apis_proto_init() }
func file_ontology_res_get_service_apis_proto_init() {
	if File_ontology_res_get_service_apis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_service_apis_proto_rawDesc), len(file_ontology_res_get_service_apis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_service_apis_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_service_apis_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_service_apis_proto_msgTypes,
	}.Build()
	File_ontology_res_get_service_apis_proto = out.File
	file_ontology_res_get_service_apis_proto_goTypes = nil
	file_ontology_res_get_service_apis_proto_depIdxs = nil
}
