// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ontology/res_get_kpi_relationships.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetKpiRelationships struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Code          string                                         `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetKpiRelationships_KpiRelationship `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetKpiRelationships_Pagination        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetKpiRelationships) Reset() {
	*x = ResponseGetKpiRelationships{}
	mi := &file_ontology_res_get_kpi_relationships_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetKpiRelationships) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetKpiRelationships) ProtoMessage() {}

func (x *ResponseGetKpiRelationships) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_kpi_relationships_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetKpiRelationships.ProtoReflect.Descriptor instead.
func (*ResponseGetKpiRelationships) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_kpi_relationships_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetKpiRelationships) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetKpiRelationships) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetKpiRelationships) GetResult() []*ResponseGetKpiRelationships_KpiRelationship {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetKpiRelationships) GetPagination() *ResponseGetKpiRelationships_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetKpiRelationships_KpiRelationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	KpiId            int64                  `protobuf:"varint,2,opt,name=kpi_id,json=kpiId,proto3" json:"kpi_id"`
	RelationType     string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type"`
	TargetType       string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type"`
	TargetId         int64                  `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id"`
	WeightSetBy      string                 `protobuf:"bytes,6,opt,name=weight_set_by,json=weightSetBy,proto3" json:"weight_set_by"`
	WeightReviewedBy string                 `protobuf:"bytes,7,opt,name=weight_reviewed_by,json=weightReviewedBy,proto3" json:"weight_reviewed_by"`
	WeightReviewedAt string                 `protobuf:"bytes,8,opt,name=weight_reviewed_at,json=weightReviewedAt,proto3" json:"weight_reviewed_at"`
	Weight           float32                `protobuf:"fixed32,9,opt,name=weight,proto3" json:"weight"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseGetKpiRelationships_KpiRelationship) Reset() {
	*x = ResponseGetKpiRelationships_KpiRelationship{}
	mi := &file_ontology_res_get_kpi_relationships_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetKpiRelationships_KpiRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetKpiRelationships_KpiRelationship) ProtoMessage() {}

func (x *ResponseGetKpiRelationships_KpiRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_kpi_relationships_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetKpiRelationships_KpiRelationship.ProtoReflect.Descriptor instead.
func (*ResponseGetKpiRelationships_KpiRelationship) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_kpi_relationships_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetKpiId() int64 {
	if x != nil {
		return x.KpiId
	}
	return 0
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetWeightSetBy() string {
	if x != nil {
		return x.WeightSetBy
	}
	return ""
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetWeightReviewedBy() string {
	if x != nil {
		return x.WeightReviewedBy
	}
	return ""
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetWeightReviewedAt() string {
	if x != nil {
		return x.WeightReviewedAt
	}
	return ""
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseGetKpiRelationships_KpiRelationship) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResponseGetKpiRelationships_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	TotalCount    int64                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetKpiRelationships_Pagination) Reset() {
	*x = ResponseGetKpiRelationships_Pagination{}
	mi := &file_ontology_res_get_kpi_relationships_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetKpiRelationships_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetKpiRelationships_Pagination) ProtoMessage() {}

func (x *ResponseGetKpiRelationships_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_kpi_relationships_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetKpiRelationships_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetKpiRelationships_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_kpi_relationships_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetKpiRelationships_Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ResponseGetKpiRelationships_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ResponseGetKpiRelationships_Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ResponseGetKpiRelationships_Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_ontology_res_get_kpi_relationships_proto protoreflect.FileDescriptor

const file_ontology_res_get_kpi_relationships_proto_rawDesc = "" +
	"\n" +
	"(ontology/res_get_kpi_relationships.proto\x12\x0etypes_ontology\"\xfd\x05\n" +
	"\x1bResponseGetKpiRelationships\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12S\n" +
	"\x06result\x18\x03 \x03(\v2;.types_ontology.ResponseGetKpiRelationships.KpiRelationshipR\x06result\x12V\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v26.types_ontology.ResponseGetKpiRelationships.PaginationR\n" +
	"pagination\x1a\xf1\x02\n" +
	"\x0fKpiRelationship\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06kpi_id\x18\x02 \x01(\x03R\x05kpiId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\x03R\btargetId\x12\"\n" +
	"\rweight_set_by\x18\x06 \x01(\tR\vweightSetBy\x12,\n" +
	"\x12weight_reviewed_by\x18\a \x01(\tR\x10weightReviewedBy\x12,\n" +
	"\x12weight_reviewed_at\x18\b \x01(\tR\x10weightReviewedAt\x12\x16\n" +
	"\x06weight\x18\t \x01(\x02R\x06weight\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x1a\x8e\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPagesB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_kpi_relationships_proto_rawDescOnce sync.Once
	file_ontology_res_get_kpi_relationships_proto_rawDescData []byte
)

func file_ontology_res_get_kpi_relationships_proto_rawDescGZIP() []byte {
	file_ontology_res_get_kpi_relationships_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_kpi_relationships_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_kpi_relationships_proto_rawDesc), len(file_ontology_res_get_kpi_relationships_proto_rawDesc)))
	})
	return file_ontology_res_get_kpi_relationships_proto_rawDescData
}

var file_ontology_res_get_kpi_relationships_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_kpi_relationships_proto_goTypes = []any{
	(*ResponseGetKpiRelationships)(nil),                 // 0: types_ontology.ResponseGetKpiRelationships
	(*ResponseGetKpiRelationships_KpiRelationship)(nil), // 1: types_ontology.ResponseGetKpiRelationships.KpiRelationship
	(*ResponseGetKpiRelationships_Pagination)(nil),      // 2: types_ontology.ResponseGetKpiRelationships.Pagination
}
var file_ontology_res_get_kpi_relationships_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetKpiRelationships.result:type_name -> types_ontology.ResponseGetKpiRelationships.KpiRelationship
	2, // 1: types_ontology.ResponseGetKpiRelationships.pagination:type_name -> types_ontology.ResponseGetKpiRelationships.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_kpi_relationships_proto_init() }
func file_ontology_res_get_kpi_relationships_proto_init() {
	if File_ontology_res_get_kpi_relationships_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_kpi_relationships_proto_rawDesc), len(file_ontology_res_get_kpi_relationships_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_kpi_relationships_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_kpi_relationships_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_kpi_relationships_proto_msgTypes,
	}.Build()
	File_ontology_res_get_kpi_relationships_proto = out.File
	file_ontology_res_get_kpi_relationships_proto_goTypes = nil
	file_ontology_res_get_kpi_relationships_proto_depIdxs = nil
}
