// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ontology/res_update_team.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseUpdateTeam struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          string                   `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        *ResponseUpdateTeam_Team `protobuf:"bytes,3,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUpdateTeam) Reset() {
	*x = ResponseUpdateTeam{}
	mi := &file_ontology_res_update_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpdateTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdateTeam) ProtoMessage() {}

func (x *ResponseUpdateTeam) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_update_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdateTeam.ProtoReflect.Descriptor instead.
func (*ResponseUpdateTeam) Descriptor() ([]byte, []int) {
	return file_ontology_res_update_team_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseUpdateTeam) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseUpdateTeam) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseUpdateTeam) GetResult() *ResponseUpdateTeam_Team {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResponseUpdateTeam_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	SlackChannel  string                 `protobuf:"bytes,3,opt,name=slack_channel,json=slackChannel,proto3" json:"slack_channel"`
	OncallEmail   string                 `protobuf:"bytes,4,opt,name=oncall_email,json=oncallEmail,proto3" json:"oncall_email"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUpdateTeam_Team) Reset() {
	*x = ResponseUpdateTeam_Team{}
	mi := &file_ontology_res_update_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUpdateTeam_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUpdateTeam_Team) ProtoMessage() {}

func (x *ResponseUpdateTeam_Team) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_update_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUpdateTeam_Team.ProtoReflect.Descriptor instead.
func (*ResponseUpdateTeam_Team) Descriptor() ([]byte, []int) {
	return file_ontology_res_update_team_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseUpdateTeam_Team) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseUpdateTeam_Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseUpdateTeam_Team) GetSlackChannel() string {
	if x != nil {
		return x.SlackChannel
	}
	return ""
}

func (x *ResponseUpdateTeam_Team) GetOncallEmail() string {
	if x != nil {
		return x.OncallEmail
	}
	return ""
}

func (x *ResponseUpdateTeam_Team) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResponseUpdateTeam_Team) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_ontology_res_update_team_proto protoreflect.FileDescriptor

const file_ontology_res_update_team_proto_rawDesc = "" +
	"\n" +
	"\x1eontology/res_update_team.proto\x12\x0etypes_ontology\"\xb6\x02\n" +
	"\x12ResponseUpdateTeam\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x06result\x18\x03 \x01(\v2'.types_ontology.ResponseUpdateTeam.TeamR\x06result\x1a\xb0\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rslack_channel\x18\x03 \x01(\tR\fslackChannel\x12!\n" +
	"\foncall_email\x18\x04 \x01(\tR\voncallEmail\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAtB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_update_team_proto_rawDescOnce sync.Once
	file_ontology_res_update_team_proto_rawDescData []byte
)

func file_ontology_res_update_team_proto_rawDescGZIP() []byte {
	file_ontology_res_update_team_proto_rawDescOnce.Do(func() {
		file_ontology_res_update_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_update_team_proto_rawDesc), len(file_ontology_res_update_team_proto_rawDesc)))
	})
	return file_ontology_res_update_team_proto_rawDescData
}

var file_ontology_res_update_team_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ontology_res_update_team_proto_goTypes = []any{
	(*ResponseUpdateTeam)(nil),      // 0: types_ontology.ResponseUpdateTeam
	(*ResponseUpdateTeam_Team)(nil), // 1: types_ontology.ResponseUpdateTeam.Team
}
var file_ontology_res_update_team_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseUpdateTeam.result:type_name -> types_ontology.ResponseUpdateTeam.Team
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ontology_res_update_team_proto_init() }
func file_ontology_res_update_team_proto_init() {
	if File_ontology_res_update_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_update_team_proto_rawDesc), len(file_ontology_res_update_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_update_team_proto_goTypes,
		DependencyIndexes: file_ontology_res_update_team_proto_depIdxs,
		MessageInfos:      file_ontology_res_update_team_proto_msgTypes,
	}.Build()
	File_ontology_res_update_team_proto = out.File
	file_ontology_res_update_team_proto_goTypes = nil
	file_ontology_res_update_team_proto_depIdxs = nil
}
