// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ontology/res_get_service_deployments.proto

package types_ontology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetServiceDeployments struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Code          string                                             `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Result        []*ResponseGetServiceDeployments_ServiceDeployment `protobuf:"bytes,3,rep,name=result,proto3" json:"result"`
	Pagination    *ResponseGetServiceDeployments_Pagination          `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServiceDeployments) Reset() {
	*x = ResponseGetServiceDeployments{}
	mi := &file_ontology_res_get_service_deployments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServiceDeployments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServiceDeployments) ProtoMessage() {}

func (x *ResponseGetServiceDeployments) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_service_deployments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServiceDeployments.ProtoReflect.Descriptor instead.
func (*ResponseGetServiceDeployments) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_service_deployments_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetServiceDeployments) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseGetServiceDeployments) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseGetServiceDeployments) GetResult() []*ResponseGetServiceDeployments_ServiceDeployment {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResponseGetServiceDeployments) GetPagination() *ResponseGetServiceDeployments_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ResponseGetServiceDeployments_ServiceDeployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	ServiceId     int64                  `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version"`
	CommitHash    string                 `protobuf:"bytes,5,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash"`
	DeployedAt    string                 `protobuf:"bytes,6,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) Reset() {
	*x = ResponseGetServiceDeployments_ServiceDeployment{}
	mi := &file_ontology_res_get_service_deployments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServiceDeployments_ServiceDeployment) ProtoMessage() {}

func (x *ResponseGetServiceDeployments_ServiceDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_service_deployments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServiceDeployments_ServiceDeployment.ProtoReflect.Descriptor instead.
func (*ResponseGetServiceDeployments_ServiceDeployment) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_service_deployments_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ResponseGetServiceDeployments_ServiceDeployment) GetDeployedAt() string {
	if x != nil {
		return x.DeployedAt
	}
	return ""
}

type ResponseGetServiceDeployments_Pagination struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextCursor     string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor"`
	PreviousCursor string                 `protobuf:"bytes,2,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor"`
	HasNext        bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next"`
	HasPrevious    bool                   `protobuf:"varint,4,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseGetServiceDeployments_Pagination) Reset() {
	*x = ResponseGetServiceDeployments_Pagination{}
	mi := &file_ontology_res_get_service_deployments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetServiceDeployments_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetServiceDeployments_Pagination) ProtoMessage() {}

func (x *ResponseGetServiceDeployments_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ontology_res_get_service_deployments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetServiceDeployments_Pagination.ProtoReflect.Descriptor instead.
func (*ResponseGetServiceDeployments_Pagination) Descriptor() ([]byte, []int) {
	return file_ontology_res_get_service_deployments_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetServiceDeployments_Pagination) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ResponseGetServiceDeployments_Pagination) GetPreviousCursor() string {
	if x != nil {
		return x.PreviousCursor
	}
	return ""
}

func (x *ResponseGetServiceDeployments_Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *ResponseGetServiceDeployments_Pagination) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *ResponseGetServiceDeployments_Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_ontology_res_get_service_deployments_proto protoreflect.FileDescriptor

const file_ontology_res_get_service_deployments_proto_rawDesc = "" +
	"\n" +
	"*ontology/res_get_service_deployments.proto\x12\x0etypes_ontology\"\xf0\x04\n" +
	"\x1dResponseGetServiceDeployments\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12W\n" +
	"\x06result\x18\x03 \x03(\v2?.types_ontology.ResponseGetServiceDeployments.ServiceDeploymentR\x06result\x12X\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v28.types_ontology.ResponseGetServiceDeployments.PaginationR\n" +
	"pagination\x1a\xc0\x01\n" +
	"\x11ServiceDeployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vcommit_hash\x18\x05 \x01(\tR\n" +
	"commitHash\x12\x1f\n" +
	"\vdeployed_at\x18\x06 \x01(\tR\n" +
	"deployedAt\x1a\xaa\x01\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12'\n" +
	"\x0fprevious_cursor\x18\x02 \x01(\tR\x0epreviousCursor\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x04 \x01(\bR\vhasPrevious\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\x16Z\x14proto/types_ontologyb\x06proto3"

var (
	file_ontology_res_get_service_deployments_proto_rawDescOnce sync.Once
	file_ontology_res_get_service_deployments_proto_rawDescData []byte
)

func file_ontology_res_get_service_deployments_proto_rawDescGZIP() []byte {
	file_ontology_res_get_service_deployments_proto_rawDescOnce.Do(func() {
		file_ontology_res_get_service_deployments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ontology_res_get_service_deployments_proto_rawDesc), len(file_ontology_res_get_service_deployments_proto_rawDesc)))
	})
	return file_ontology_res_get_service_deployments_proto_rawDescData
}

var file_ontology_res_get_service_deployments_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ontology_res_get_service_deployments_proto_goTypes = []any{
	(*ResponseGetServiceDeployments)(nil),                   // 0: types_ontology.ResponseGetServiceDeployments
	(*ResponseGetServiceDeployments_ServiceDeployment)(nil), // 1: types_ontology.ResponseGetServiceDeployments.ServiceDeployment
	(*ResponseGetServiceDeployments_Pagination)(nil),        // 2: types_ontology.ResponseGetServiceDeployments.Pagination
}
var file_ontology_res_get_service_deployments_proto_depIdxs = []int32{
	1, // 0: types_ontology.ResponseGetServiceDeployments.result:type_name -> types_ontology.ResponseGetServiceDeployments.ServiceDeployment
	2, // 1: types_ontology.ResponseGetServiceDeployments.pagination:type_name -> types_ontology.ResponseGetServiceDeployments.Pagination
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ontology_res_get_service_deployments_proto_init() }
func file_ontology_res_get_service_deployments_proto_init() {
	if File_ontology_res_get_service_deployments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ontology_res_get_service_deployments_proto_rawDesc), len(file_ontology_res_get_service_deployments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ontology_res_get_service_deployments_proto_goTypes,
		DependencyIndexes: file_ontology_res_get_service_deployments_proto_depIdxs,
		MessageInfos:      file_ontology_res_get_service_deployments_proto_msgTypes,
	}.Build()
	File_ontology_res_get_service_deployments_proto = out.File
	file_ontology_res_get_service_deployments_proto_goTypes = nil
	file_ontology_res_get_service_deployments_proto_depIdxs = nil
}
