MODULE = $(shell go list -m)
VERSION ?= $(shell git describe --tags --always --dirty --match=v* 2> /dev/null || echo "1.0.0")
PACKAGES := $(shell go list ./... | grep -v /vendor/)
LDFLAGS := -ldflags "-X main.Version=${VERSION}"
GO := go

SHELL := /bin/bash

PID_FILE := './.pid'
FSWATCH_FILE := './fswatch.cfg'

.PHONY: default
default: help

# generate help info from comments: thanks to https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
.PHONY: help
help: ## help information about make commands
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

.PHONY: run
run: ## run the API server
	go run ${LDFLAGS} cmd/server/main.go

.PHONY: seed
seed: ## insert seed data into the database
	go run ${LDFLAGS} cmd/seed/seed.go

.PHONY: run-restart
run-restart: ## restart the API server
	@pkill -P `cat $(PID_FILE)` || true
	@printf '%*s\n' "80" '' | tr ' ' -
	@echo "Source file changed. Restarting server..."
	@go run ${LDFLAGS} cmd/server/main.go & echo $$! > $(PID_FILE)
	@printf '%*s\n' "80" '' | tr ' ' -

# run-live: ## run the API server with live reload support (requires fswatch)
# 	@echo "copying git hooks"
# 	@cp -R hooks hooks .git
# 	@go run ${LDFLAGS} cmd/server/main.go & echo $$! > $(PID_FILE)
# 	@fswatch -x -o --event Created --event Updated --event Renamed -r internal pkg cmd config | xargs -n1 -I {} make run-restart
run-live: ## run the API server with live reload support (requires fswatch)
	@echo "copying git hooks"
	@cp -R hooks ../.git/hooks
	@go run ${LDFLAGS} cmd/server/main.go & echo $$! > $(PID_FILE)
	@fswatch -x -o --event Created --event Updated --event Renamed -r internal pkg cmd config | xargs -n1 -I {} make run-restart

.PHONY: build
build:  ## build the API server binary
	CGO_ENABLED=0 go build ${LDFLAGS} -a -o server $(MODULE)/cmd/server

.PHONY: build-docker
build-docker: ## build the API server as a docker image
	docker build -f cmd/server/Dockerfile -t server .

.PHONY: clean
clean: ## remove temporary files
	rm -rf server coverage.out coverage-all.out

.PHONY: version
version: ## display the version of the API server
	@echo $(VERSION)

.PHONY: test
test: ## Run tests
	$(GO) test -v ./...

.PHONY: fmt
fmt: ## Format Go code
	$(GO) fmt ./...

.PHONY: vet
vet: ## Run go vet
	$(GO) vet ./...

.PHONY: lint
lint: fmt vet ## Run formatters and linters
	$(GO) mod tidy

.PHONY: clean-install
clean-install: ## clean install dependencies
	@GOPRIVATE="app/ontology" go mod tidy

.PHONY: migrate-new
migrate-new: ## create a new database migration
	@read -p "Enter the name of the new migration: " name; \
	timestamp=$(shell date +%Y%m%d%H%M%S); \
	filename="$${timestamp}_$${name// /_}"; \
	touch "migrations/postgres/$${filename}.up.sql" "migrations/postgres/$${filename}.down.sql"; \
	touch "migrations/mysql/$${filename}.up.sql" "migrations/mysql/$${filename}.down.sql"; \
	touch "migrations/clickhouse/$${filename}.up.sql" "migrations/clickhouse/$${filename}.down.sql"; \
	echo "Created migrations: $${filename}.up.sql and $${filename}.down.sql"