// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: watchlist/req_create_watchlist.proto

/* eslint-disable */

export const protobufPackage = "types_watchlist";

/** POST: /oms/v1/watchlist */
export interface RequestCreateWatchlist {
  name: string;
}
