// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: watchlist/res_create_watchlist.proto

/* eslint-disable */

export const protobufPackage = "types_watchlist";

/** POST: /oms/v1/watchlist */
export interface ResponseCreateWatchlist {
  code: string;
  message: string;
  watchlist: ResponseCreateWatchlist_Watchlist | undefined;
}

export interface ResponseCreateWatchlist_Watchlist {
  id: string;
  name: string;
  is_fav: boolean;
}
