// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: entity/req_create_entity.proto

/* eslint-disable */

export const protobufPackage = "types_entity";

/** POST: /ontology/v1/entities/create */
export interface RequestCreateEntity {
  general_data: GeneralData | undefined;
  user_data?: UserData | undefined;
  business_data?: BusinessData | undefined;
  document_data: DocumentData[];
  instrument_ids?: InstrumentIDs | undefined;
  communication_data?: CommunicationData | undefined;
  location_data: LocationData[];
  risk_scores: RiskScoreData[];
  custom_data: { [key: string]: string };
  relationships?: Relationships | undefined;
  options?: Options | undefined;
}

export interface RequestCreateEntity_CustomDataEntry {
  key: string;
  value: string;
}

export interface GeneralData {
  entity_id: string;
  entity_type: string;
  entity_subtype?: string | undefined;
  status?: string | undefined;
  registered_at: string;
  tags: string[];
}

export interface UserData {
  first_name?: string | undefined;
  middle_name?: string | undefined;
  last_name?: string | undefined;
  day_of_birth?: number | undefined;
  month_of_birth?: number | undefined;
  year_of_birth?: number | undefined;
  /** enum: male, female, other */
  gender?: string | undefined;
  ssn?: string | undefined;
  id?: string | undefined;
}

export interface BusinessData {
  business_name?: string | undefined;
  corporate_tax_id?: string | undefined;
  account_holder_name?: string | undefined;
  registered_state?: string | undefined;
  registered_country?: string | undefined;
  doing_business_as?: string | undefined;
  website?: string | undefined;
  id?: string | undefined;
}

export interface DocumentData {
  document_id: string;
  document_type: string;
  state?: string | undefined;
  country?: string | undefined;
  issued_at?: string | undefined;
  expires_at?: string | undefined;
}

export interface InstrumentIDs {
  instrument_ids: string[];
}

export interface CommunicationData {
  email_addresses: string[];
  phone_numbers: string[];
}

export interface LocationData {
  type?: string | undefined;
  building_number?: string | undefined;
  unit_number?: string | undefined;
  street_name?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postal_code?: string | undefined;
  country?: string | undefined;
  id?: string | undefined;
}

export interface RiskScoreData {
  name: string;
  score: string;
  denominator: string;
  id?: string | undefined;
}

export interface Relationships {
  parents: ParentRelationship[];
  children: ChildRelationship[];
  instruments: InstrumentRelationship[];
}

export interface ParentRelationship {
  entity_id: string;
  relationship_id: string;
  entity_type: string;
  id?: string | undefined;
}

export interface ChildRelationship {
  entity_id: string;
  relationship_id: string;
  entity_type: string;
  id?: string | undefined;
}

export interface InstrumentRelationship {
  instrument_id: string;
  relationship_id: string;
  id?: string | undefined;
}

export interface Options {
  resolve_geoip?: boolean | undefined;
  merge_custom_data?: boolean | undefined;
  upsert_on_conflict?: boolean | undefined;
  monitor?: number | undefined;
}
