// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: entity/res_create_entity.proto

/* eslint-disable */

export const protobufPackage = "types_entity";

/** Response for POST: /ontology/v1/entities/create */
export interface ResponseCreateEntity {
  code: string;
  message: string;
  result?: EntityData | undefined;
}

export interface EntityData {
  entity_id: string;
  entity_type: string;
  entity_subtype?: string | undefined;
  status?: string | undefined;
  registered_at: string;
  user_data_id?: string | undefined;
  business_data_id?: string | undefined;
  document_ids: string[];
  location_ids: string[];
  risk_score_ids: string[];
  created_at: string;
  updated_at: string;
}
