// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: watchlist/res_create_watchlist.proto

package types_watchlist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// POST: /oms/v1/watchlist
type ResponseCreateWatchlist struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Code          string                             `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Watchlist     *ResponseCreateWatchlist_Watchlist `protobuf:"bytes,3,opt,name=watchlist,proto3" json:"watchlist"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateWatchlist) Reset() {
	*x = ResponseCreateWatchlist{}
	mi := &file_watchlist_res_create_watchlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateWatchlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateWatchlist) ProtoMessage() {}

func (x *ResponseCreateWatchlist) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_res_create_watchlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateWatchlist.ProtoReflect.Descriptor instead.
func (*ResponseCreateWatchlist) Descriptor() ([]byte, []int) {
	return file_watchlist_res_create_watchlist_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseCreateWatchlist) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResponseCreateWatchlist) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseCreateWatchlist) GetWatchlist() *ResponseCreateWatchlist_Watchlist {
	if x != nil {
		return x.Watchlist
	}
	return nil
}

type ResponseCreateWatchlist_Watchlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	IsFav         bool                   `protobuf:"varint,3,opt,name=is_fav,json=isFav,proto3" json:"is_fav"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateWatchlist_Watchlist) Reset() {
	*x = ResponseCreateWatchlist_Watchlist{}
	mi := &file_watchlist_res_create_watchlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateWatchlist_Watchlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateWatchlist_Watchlist) ProtoMessage() {}

func (x *ResponseCreateWatchlist_Watchlist) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_res_create_watchlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateWatchlist_Watchlist.ProtoReflect.Descriptor instead.
func (*ResponseCreateWatchlist_Watchlist) Descriptor() ([]byte, []int) {
	return file_watchlist_res_create_watchlist_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseCreateWatchlist_Watchlist) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseCreateWatchlist_Watchlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseCreateWatchlist_Watchlist) GetIsFav() bool {
	if x != nil {
		return x.IsFav
	}
	return false
}

var File_watchlist_res_create_watchlist_proto protoreflect.FileDescriptor

const file_watchlist_res_create_watchlist_proto_rawDesc = "" +
	"\n" +
	"$watchlist/res_create_watchlist.proto\x12\x0ftypes_watchlist\"\xe1\x01\n" +
	"\x17ResponseCreateWatchlist\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12P\n" +
	"\twatchlist\x18\x03 \x01(\v22.types_watchlist.ResponseCreateWatchlist.WatchlistR\twatchlist\x1aF\n" +
	"\tWatchlist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_fav\x18\x03 \x01(\bR\x05isFavB\x17Z\x15proto/types_watchlistb\x06proto3"

var (
	file_watchlist_res_create_watchlist_proto_rawDescOnce sync.Once
	file_watchlist_res_create_watchlist_proto_rawDescData []byte
)

func file_watchlist_res_create_watchlist_proto_rawDescGZIP() []byte {
	file_watchlist_res_create_watchlist_proto_rawDescOnce.Do(func() {
		file_watchlist_res_create_watchlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watchlist_res_create_watchlist_proto_rawDesc), len(file_watchlist_res_create_watchlist_proto_rawDesc)))
	})
	return file_watchlist_res_create_watchlist_proto_rawDescData
}

var file_watchlist_res_create_watchlist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_watchlist_res_create_watchlist_proto_goTypes = []any{
	(*ResponseCreateWatchlist)(nil),           // 0: types_watchlist.ResponseCreateWatchlist
	(*ResponseCreateWatchlist_Watchlist)(nil), // 1: types_watchlist.ResponseCreateWatchlist.Watchlist
}
var file_watchlist_res_create_watchlist_proto_depIdxs = []int32{
	1, // 0: types_watchlist.ResponseCreateWatchlist.watchlist:type_name -> types_watchlist.ResponseCreateWatchlist.Watchlist
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_watchlist_res_create_watchlist_proto_init() }
func file_watchlist_res_create_watchlist_proto_init() {
	if File_watchlist_res_create_watchlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watchlist_res_create_watchlist_proto_rawDesc), len(file_watchlist_res_create_watchlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watchlist_res_create_watchlist_proto_goTypes,
		DependencyIndexes: file_watchlist_res_create_watchlist_proto_depIdxs,
		MessageInfos:      file_watchlist_res_create_watchlist_proto_msgTypes,
	}.Build()
	File_watchlist_res_create_watchlist_proto = out.File
	file_watchlist_res_create_watchlist_proto_goTypes = nil
	file_watchlist_res_create_watchlist_proto_depIdxs = nil
}
