// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/req_create_rule.proto

/* eslint-disable */

export const protobufPackage = "types_rules";

/** POST: /ontology/v1/rules/create */
export interface RequestCreateRule {
  name: string;
  duration_value?: number | undefined;
  duration_unit?: string | undefined;
  status?: string | undefined;
  condition_groups: ConditionGroup[];
  deploy_start_date?: number | undefined;
  deploy_end_date?: number | undefined;
  description?: string | undefined;
  rule_type?: string | undefined;
  source?: string | undefined;
  tags?: string | undefined;
  group_by_field?: string | undefined;
  target_table?: string | undefined;
}

export interface ConditionGroup {
  /** 'AND', 'OR' */
  group_operator?: string | undefined;
  group_order?: number | undefined;
  conditions: RuleCondition[];
}

export interface RuleCondition {
  /** 'AND', 'OR' */
  logical_operator?: string | undefined;
  field_name: string;
  /** '>=', '<=', '=', '!=', etc. */
  operator: string;
  value?: string | undefined;
  /** 'sum', 'avg', 'count' */
  aggregate_function?: string | undefined;
}
