// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/req_get_rule.proto

/* eslint-disable */

export const protobufPackage = "types_rules";

/** GET: /ontology/v1/rules/:id */
export interface RequestGetRule {
  id: string;
}
