// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/req_list_rules.proto

/* eslint-disable */

export const protobufPackage = "types_rules";

/** GET: /ontology/v1/rules */
export interface RequestListRules {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
  status?: string | undefined;
}
