// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/req_run_rule.proto

/* eslint-disable */

export const protobufPackage = "types_rules";

/** POST: /ontology/v1/rules/run */
export interface RequestRunRule {
  id: string;
  debug?: boolean | undefined;
  limit?: number | undefined;
}
