// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/req_update_rule.proto

/* eslint-disable */
import type { ConditionGroup } from "./req_create_rule";

export const protobufPackage = "types_rules";

/** POST: /ontology/v1/rules/update */
export interface RequestUpdateRule {
  id: string;
  name?: string | undefined;
  duration_value?: number | undefined;
  duration_unit?: string | undefined;
  status?: string | undefined;
  condition_groups: ConditionGroup[];
  deploy_start_date?: string | undefined;
  deploy_end_date?: string | undefined;
  description?: string | undefined;
  rule_type?: string | undefined;
  source?: string | undefined;
  tags?: string | undefined;
  group_by_field?: string | undefined;
  target_table?: string | undefined;
}
