// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/res_update_rule.proto

/* eslint-disable */
import type { RuleData } from "./res_create_rule";

export const protobufPackage = "types_rules";

/** Response for POST: /ontology/v1/rules/update */
export interface ResponseUpdateRule {
  code: string;
  message: string;
  result?: RuleData | undefined;
}
