// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/res_create_rule.proto

/* eslint-disable */

export const protobufPackage = "types_rules";

/** Response for POST: /ontology/v1/rules/create */
export interface ResponseCreateRule {
  code: string;
  message: string;
  result?: RuleData | undefined;
}

export interface RuleData {
  id: string;
  name: string;
  status: string;
  deploy_start_date?: string | undefined;
  deploy_end_date?: string | undefined;
  description?: string | undefined;
  rule_type?: string | undefined;
  source?: string | undefined;
  tags?: string | undefined;
  created_at: string;
  updated_at: string;
  group_by_field?: string | undefined;
  target_table?: string | undefined;
}
