// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/res_run_rule.proto

/* eslint-disable */

export const protobufPackage = "types_rules";

/** Response for POST: /ontology/v1/rules/run */
export interface ResponseRunRule {
  code: string;
  message: string;
  result: RunRuleResult | undefined;
}

export interface RunRuleResult {
  events: RuleEvent[];
  query?: string | undefined;
  error?: string | undefined;
  count: string;
}

export interface RuleEvent {
  event_id: string;
  event_time: string;
  columns: { [key: string]: string };
}

export interface RuleEvent_ColumnsEntry {
  key: string;
  value: string;
}
