// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/res_get_rule.proto

/* eslint-disable */
import type { ConditionGroup } from "./req_create_rule";

export const protobufPackage = "types_rules";

/** Response for GET: /ontology/v1/rules/:id */
export interface ResponseGetRule {
  code: string;
  message: string;
  result: RuleDetailData | undefined;
}

export interface RuleDetailData {
  id: string;
  name: string;
  status: string;
  deploy_start_date?: string | undefined;
  deploy_end_date?: string | undefined;
  description?: string | undefined;
  rule_type?: string | undefined;
  source?: string | undefined;
  tags?: string | undefined;
  created_at: string;
  updated_at: string;
  condition_groups: ConditionGroup[];
  duration_value?: number | undefined;
  duration_unit?: string | undefined;
  group_by_field?: string | undefined;
  target_table?: string | undefined;
}
