// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: rules/res_list_rules.proto

/* eslint-disable */
import type { RuleData } from "./res_create_rule";

export const protobufPackage = "types_rules";

/** Response for GET: /ontology/v1/rules */
export interface ResponseListRules {
  code: string;
  message: string;
  result: RuleListData | undefined;
}

export interface RuleListData {
  rules: RuleData[];
  pagination: Pagination | undefined;
}

export interface Pagination {
  total: number;
  page: number;
  limit: number;
}
