// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: dictionary/req_list_dictionary.proto

/* eslint-disable */

export const protobufPackage = "types_dictionary";

/** Response for GET: /ontology/v1/dictionary/list:type */
export interface ResponseListDictionary {
  code: string;
  message: string;
  result: ResponseListDictionary_Dictionary[];
}

export interface ResponseListDictionary_Dictionary {
  id: number;
  name: string;
  description: string;
  code: string;
  type: string;
}
