// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: columns/req_list_columns.proto

/* eslint-disable */

export const protobufPackage = "types_columns";

/** GET: /ontology/v1/columns/list */
export interface RequestListColumns {
  column?: string | undefined;
  table?: string | undefined;
}
