// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: columns/res_list_columns.proto

/* eslint-disable */

export const protobufPackage = "types_columns";

/** Response for GET: /ontology/v1/columns/list */
export interface ResponseListColumns {
  code: string;
  message: string;
  results: ColumnItem[];
}

export interface ColumnItem {
  table: string;
  column: string;
  name: string;
  type: string;
}
