// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: custom_data/req_create_custom_data.proto

/* eslint-disable */

export const protobufPackage = "types_custom_data";

/** POST: /ontology/v1/custom-data/create */
export interface RequestCreateCustomData {
  id: string;
  name: string;
  /** (instrument, entity, event, transaction) */
  type: string;
}
