// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: custom_data/res_create_custom_data.proto

/* eslint-disable */

export const protobufPackage = "types_custom_data";

/** Response for POST: /ontology/v1/custom-data/create */
export interface ResponseCreateCustomData {
  code: string;
  message: string;
  data?: CustomData | undefined;
}

export interface CustomData {
  id: string;
  name: string;
  type: string;
  created_at: string;
}
