// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: custom_data/res_get_custom_data.proto

/* eslint-disable */

export const protobufPackage = "types_custom_data";

/** GET: /ontology/v1/custom-data */
export interface ResponseGetCustomData {
  code: string;
  message: string;
  result: ResponseGetCustomData_Result | undefined;
}

export interface ResponseGetCustomData_Result {
  data: CustomDataItem[];
}

export interface CustomDataItem {
  name: string;
  type: string;
  formatted_name: string;
}
