// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: custom_data/res_search_custom_data.proto

/* eslint-disable */
import type { CustomData } from "./res_create_custom_data";

export const protobufPackage = "types_custom_data";

/** Response for GET: /ontology/v1/custom-data/search */
export interface ResponseSearchCustomData {
  code: string;
  message: string;
  data: CustomData[];
}
