// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: instruments/req_create_instrument.proto

/* eslint-disable */

export const protobufPackage = "types_instruments";

/** POST: /ontology/v1/instruments/create */
export interface RequestCreateInstrument {
  instrument_id: string;
  instrument_type: string;
  subtype?: string | undefined;
  source: string;
  name?: string | undefined;
  status?: string | undefined;
  registered_at: string;
  parent_instrument_id?: string | undefined;
  entities: InstrumentEntity[];
  digital_data?: InstrumentDigitalData | undefined;
  tags: string[];
  custom_data: { [key: string]: string };
  monitor: number;
}

export interface RequestCreateInstrument_CustomDataEntry {
  key: string;
  value: string;
}

export interface InstrumentEntity {
  entity_id: string;
  relationship_id: string;
  entity_type: string;
}

export interface InstrumentDigitalData {
  ip_addresses: string[];
  client_fingerprints: string[];
  location_data: InstrumentLocation[];
}

export interface InstrumentLocation {
  type?: string | undefined;
  building_number?: string | undefined;
  unit_number?: string | undefined;
  street_name?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postal_code?: string | undefined;
  country?: string | undefined;
}
