// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: instruments/res_get_instrument.proto

/* eslint-disable */

export const protobufPackage = "types_instruments";

/** Response for GET: /ontology/v1/instruments/:id */
export interface ResponseGetInstrument {
  code: string;
  message: string;
  result?: InstrumentDetails | undefined;
}

export interface InstrumentDetails {
  instrument_id: string;
  instrument_type: string;
  subtype?: string | undefined;
  source: string;
  name?: string | undefined;
  status?: string | undefined;
  registered_at: string;
  parent_instrument_id?: string | undefined;
  digital_ip_addresses: string[];
  digital_client_fingerprints: string[];
  tags: string[];
  custom_data: { [key: string]: string };
  /** UInt8 in ClickHouse -> int32 in proto usually, or uint32 */
  monitor: number;
  created_at: string;
  updated_at: string;
}

export interface InstrumentDetails_CustomDataEntry {
  key: string;
  value: string;
}
