// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: instruments/res_create_instrument.proto

/* eslint-disable */

export const protobufPackage = "types_instruments";

/** Response for POST: /ontology/v1/instruments/create */
export interface ResponseCreateInstrument {
  code: string;
  message: string;
  result?: InstrumentData | undefined;
}

export interface InstrumentData {
  instrument_id: string;
  instrument_type: string;
  registered_at: string;
  created_at: string;
  updated_at: string;
}
