// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/req_update_entity.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface RequestUpdateEntity {
  name?: string | undefined;
  description?:
    | string
    | undefined;
  /** Not for FE to edit */
  code?: string | undefined;
  display_order?: number | undefined;
  is_start?: boolean | undefined;
  is_terminal?: boolean | undefined;
  feature_id?: string | undefined;
  api_ids: string[];
}
