// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/req_update_team.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface RequestUpdateTeam {
  name?: string | undefined;
  slack_channel?:
    | string
    | undefined;
  /** Comma separated emails */
  oncall_email?: string | undefined;
}
