// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/req_create_team.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface RequestCreateTeam {
  name: string;
  slack_channel: string;
  /** Comma separated emails */
  oncall_email: string;
}
