// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/req_create_entity.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface RequestCreateEntity {
  feature_id: string;
  code: string;
  name: string;
  description: string;
  display_order: number;
  is_start: boolean;
  is_terminal: boolean;
  api_ids: string[];
}
