// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/req_update_feature.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface RequestUpdateFeature {
  name?: string | undefined;
  description?: string | undefined;
  is_active?: boolean | undefined;
}
