// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_create_team.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseCreateTeam {
  code: string;
  message: string;
  result: ResponseCreateTeam_Team | undefined;
}

export interface ResponseCreateTeam_Team {
  id: string;
  name: string;
  slack_channel: string;
  oncall_email: string;
  created_at: string;
  updated_at: string;
}
