// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_create_entity.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseCreateEntity {
  code: string;
  message: string;
  result: ResponseCreateEntity_Result | undefined;
}

export interface ResponseCreateEntity_Result {
  id: string;
  feature_id: string;
  code: string;
  name: string;
  description: string;
  display_order: number;
  is_start: boolean;
  is_terminal: boolean;
  created_at: string;
  updated_at: string;
}
