// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_services.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetServices {
  code: string;
  message: string;
  data: ResponseGetServices_Service[];
  pagination: ResponseGetServices_Pagination | undefined;
}

export interface ResponseGetServices_Service {
  id: string;
  code: string;
  name: string;
  criticality_level: string;
  updated_at: string;
  repository_url: string;
}

export interface ResponseGetServices_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
