// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_teams.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetTeams {
  code: string;
  message: string;
  result: ResponseGetTeams_Team[];
  pagination: ResponseGetTeams_Pagination | undefined;
}

export interface ResponseGetTeams_Team {
  id: string;
  name: string;
  slack_channel: string;
  oncall_email: string;
  role_name: string;
}

export interface ResponseGetTeams_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
