// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_update_feature.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseUpdateFeature {
  code: string;
  message: string;
  result: ResponseUpdateFeature_Result | undefined;
}

export interface ResponseUpdateFeature_Result {
  id: string;
  name: string;
  code: string;
  description: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
