// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_feature_metrics.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetFeatureMetrics {
  code: string;
  message: string;
  result: ResponseGetFeatureMetrics_FeatureMetric | undefined;
}

export interface ResponseGetFeatureMetrics_FeatureMetric {
  window_start: string;
  window_minutes: number;
  total_count: string;
  success_rate: number;
  failure_rate: number;
  p50_duration_ms: number;
  p95_duration_ms: number;
  p99_duration_ms: number;
  created_at: string;
}
