// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_entity_transitions.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetEntityTransitions {
  code: string;
  message: string;
  result: ResponseGetEntityTransitions_Transition[];
}

export interface ResponseGetEntityTransitions_Transition {
  id: string;
  from_entity_id: string;
  to_entity_id: string;
  condition_expression: string;
  transition_type: string;
  condition_description: string;
}
