// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_apis.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetApis {
  code: string;
  message: string;
  result: ResponseGetApis_Api[];
  pagination: ResponseGetApis_Pagination | undefined;
}

export interface ResponseGetApis_Api {
  id: string;
  endpoint: string;
  method: string;
  protocol: string;
  is_internal: boolean;
  created_at: string;
}

export interface ResponseGetApis_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
