// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_kpis.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetKpis {
  code: string;
  message: string;
  result: ResponseGetKpis_Kpi[];
  pagination: ResponseGetKpis_Pagination | undefined;
}

export interface ResponseGetKpis_Kpi {
  id: string;
  code: string;
  name: string;
  description: string;
  metric_type: string;
  unit: string;
  created_at: string;
  updated_at: string;
}

export interface ResponseGetKpis_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
