// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_feature_teams.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetFeatureTeams {
  code: string;
  message: string;
  result: ResponseGetFeatureTeams_Team[];
}

export interface ResponseGetFeatureTeams_Team {
  team_id: string;
  team_name: string;
  role_name: string;
}
