// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_entity_apis.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetEntityApis {
  code: string;
  message: string;
  data: ResponseGetEntityApis_Api[];
  pagination: ResponseGetEntityApis_Pagination | undefined;
}

export interface ResponseGetEntityApis_Api {
  id: string;
  service_identifier: string;
  endpoint: string;
  method: string;
  is_internal: boolean;
  description: string;
}

export interface ResponseGetEntityApis_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
