// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_feature_instances.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetFeatureInstances {
  code: string;
  message: string;
  result: ResponseGetFeatureInstances_FeatureInstance[];
  pagination: ResponseGetFeatureInstances_Pagination | undefined;
}

export interface ResponseGetFeatureInstances_FeatureInstance {
  id: string;
  feature_id: string;
  status: string;
  started_at: string;
  completed_at: string;
}

export interface ResponseGetFeatureInstances_Pagination {
  next_cursor: string;
  previous_cursor: string;
  has_next: boolean;
  has_previous: boolean;
  limit: number;
}
