// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_service_apis.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetServiceApis {
  code: string;
  message: string;
  data: ResponseGetServiceApis_Api[];
  pagination: ResponseGetServiceApis_Pagination | undefined;
}

export interface ResponseGetServiceApis_Api {
  id: string;
  endpoint: string;
  http_method: string;
  is_internal: boolean;
  description: string;
  version: string;
  created_at: string;
}

export interface ResponseGetServiceApis_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
