// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_kpi_relationships.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetKpiRelationships {
  code: string;
  message: string;
  result: ResponseGetKpiRelationships_KpiRelationship[];
  pagination: ResponseGetKpiRelationships_Pagination | undefined;
}

export interface ResponseGetKpiRelationships_KpiRelationship {
  id: string;
  kpi_id: string;
  relation_type: string;
  target_type: string;
  target_id: string;
  weight_set_by: string;
  weight_reviewed_by: string;
  weight_reviewed_at: string;
  weight: number;
  created_at: string;
  updated_at: string;
}

export interface ResponseGetKpiRelationships_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
