// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_features.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetFeatures {
  code: string;
  message: string;
  result: ResponseGetFeatures_Feature[];
  pagination: ResponseGetFeatures_Pagination | undefined;
}

export interface ResponseGetFeatures_Feature {
  id: string;
  code: string;
  name: string;
  description: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ResponseGetFeatures_Pagination {
  current_page: number;
  page_size: number;
  total_count: string;
  total_pages: number;
}
