// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: ontology/res_get_service_deployments.proto

/* eslint-disable */

export const protobufPackage = "types_ontology";

export interface ResponseGetServiceDeployments {
  code: string;
  message: string;
  result: ResponseGetServiceDeployments_ServiceDeployment[];
  pagination: ResponseGetServiceDeployments_Pagination | undefined;
}

export interface ResponseGetServiceDeployments_ServiceDeployment {
  id: string;
  service_id: string;
  environment: string;
  version: string;
  commit_hash: string;
  deployed_at: string;
}

export interface ResponseGetServiceDeployments_Pagination {
  next_cursor: string;
  previous_cursor: string;
  has_next: boolean;
  has_previous: boolean;
  limit: number;
}
